### ISSUE TITLE
Add a "Shrink disk" menu item

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-vm#101]
The virtual disk of the GNS3 VM can get really big. Even after deleting some images, the VM disk size wouldn't get lower. What about a "Shrink disk" menu item, that calls the VMware/Virtualbox tools to shrink the disk.

In VMware it would be "sudo vmware-toolbox-cmd disk shrink /opt".

**Comment by grossmj** [comment]
Where would you see that menu item?

**Comment by ehlers** [comment]
Well, the GNS3-VM doesn't have that many menus. I was thinking about this one:
![gns3vm_menu](https://user-images.githubusercontent.com/896406/37147550-96e02dfa-22c7-11e8-9b47-a969a5ef1779.png)

For VMware the disk shrinking commands would be something like this:
```
sudo service gns3 stop
sudo service docker stop
sudo vmware-toolbox-cmd disk shrink /opt
sudo vmware-toolbox-cmd disk shrink /
sudo reboot
```
To be on the safe side, I'm stopping the services before the disk shrinking and reboot afterwards. Of course a warning with the possibility to cancel should be shown before.

I'm not sure, if VirtualBox has something comparable.

**Comment by ehlers** [comment]
Looks good.

**Comment by LuminisIndia** [comment]
@ehlers @grossmj 
I have already installed GNS3 VM v2.1.8, but in menu, there is no 'Shrink' function currently.  How can I add this to my installation?
With thanks,
Meena
