### ISSUE TITLE
Virtualbox: KVM support available false

### ISSUE THREAD

**Issue by nqb** [GNS3/gns3-vm#109]
Hello,

With GNS3.VM.VirtualBox.2.1.11, downloaded from website, if I import GNS3 VM.ova, I get "KVM Support available: false" on the ncurse interface.

My config:
- Ubuntu 18.04 up-to-date
- Virtualbox 5.2.22 r126460 (Qt5.9.5)
- Guest additions 5.2.20

**Comment by grossmj** [comment]
KVM (nested virtualization) is not supported by VirtualBox. This is why we recommend to use VMware Workstation Player 14 or VMware Workstation pro 15 to use with GNS3.

**Comment by nqb** [comment]
@grossmj,

Thanks for you reply. In the GNS3 project, which is the aim of Virtualbox VM ?

**Comment by grossmj** [comment]
VirtualBox VMs can be used to run anything like Linux etc. It is just another way to run hosts/appliances in addition of VMware and Qemu.

> I didn't find a way and documentation to start a wizard from Virtualbox.

Not sure what you mean here.

**Comment by nqb** [comment]
How do you run the wizard from a Virtualbox VM ? I didn't find any documentation that explain this.

**Comment by grossmj** [comment]
Simply create VirtualBox VMs in VirtualBox and then add them in the GNS3 preferences.

![add_virtualbox_vm](https://user-images.githubusercontent.com/4752614/49073272-a1ccb900-f264-11e8-85e9-c29c56b44d63.png)

**Comment by grossmj** [comment]
It looks like VirtualBox will support nested virtualization soon (version 6 suppots AMD only at the moment).

**Comment by yakbu002** [comment]
I am trying to make GNS3 work with VirtualBox, I still could not open the nested virtualization. I enabled everything related to hardware virtualization, I have AMD processor and I made sure I have virtualization is enabled and on the PC and VirtualBox GNS3 VM appliance system settings. But still no chance on making it to say KVM support enabled. Please let me know if it is possible or I am missing something. Thanks!

**Comment by grossmj** [comment]
Can you post a screenshot of the VirtualBox VM settings?

![Screenshot from 2022-08-28 22-26-35](https://user-images.githubusercontent.com/4752614/187093182-ba53bfa2-198c-4efc-91c6-b58291368677.png)

Thanks!

**Comment by yakbu002** [comment]
Thank you for your response. I have found the problem actually. Even though I tried everything on vbox and even in VMware it was not working because I had hiperV activated and windows was prioritizing hiperV so the virtualization was not available for vbox and vmware. I found a power shell command on VMware answers. And after running it, it worked. Actually now it works on both of them. Both vbox and VMware. So thank you again.

**Comment by grossmj** [comment]
Perfect, thanks for the info! 👍

**Comment by deanwelsh7** [comment]
@yakbu002 are you able to paste the power shell command for the fix?  I'm having trouble finding it

**Comment by yakbu002** [comment]
Hi @deanwelsh7 , 
I have found the link to answer this. it is not direct answer but if you read through the reddit page you can see it. look for -an0m4ly-'s comments.

**Comment by chih1roo** [comment]
hi, i also had a problem on my VM, it says the same thing (i used VM version 7.0)  it keep saying my kvm support : false, i enabled virtualization and disable hyperV but those wont fix my problem, do you have any idea please? im pretty stressed because it's for my winbox task

thank you

**Comment by anuonem** [comment]
<img width="490" alt="KVM" src="https://github.com/user-attachments/assets/e3ce4dbe-25e6-49e5-b010-5483c161abe3">
BONSOIR SVP J AI LE MEME PROBLÈME   MON  KVM SUPPORTS  AFFICHE FALSE   J UTILISE VMWARE WORKSTATION 17 J AI UNE MACHINE DELL  LATITUDE 5400  D'APRES  MON FABRICANT MA MACHINE EST  SUPPORTER  INTEL VT-X MAIS   RIEN  J AI DÉSACTIVÉ  HYPER-V  D APRES  CERTAINE RECOMMANDATION   MAIS RIEN  
<img width="245" alt="U" src="https://github.com/user-attachments/assets/a14a0955-3c5a-4698-b708-2f10406dfd30">
<img width="286" alt="J" src="https://github.com/user-attachments/assets/2bc92482-7bd6-4629-8d65-22b3c76f727c">
<img width="239" alt="JU" src="https://github.com/user-attachments/assets/a8d2f638-ac99-4435-8802-7795670238f3">

**Comment by anuonem** [comment]
<img width="239" alt="JU" src="https://github.com/user-attachments/assets/673118ff-245e-4d71-87de-c34c3181f02d">

**Comment by anuonem** [comment]
<img width="286" alt="J" src="https://github.com/user-attachments/assets/75d3ce17-ee9b-49c0-b6c7-990b741ced66">

**Comment by HarishM-git** [comment]
bro even though i disabled the hyperV i am still unable to set the kvm support to true , can any one help me to rectify it
