### ISSUE TITLE
Upgrading through the GNS3 VM's UI is broken when behind a Proxy

### ISSUE THREAD

**Issue by RyanBreaker** [GNS3/gns3-vm#110]
When the VM is behind a Proxy and is configured for it, the Upgrade function from the VM's UI is broken at the `add-apt-repository` lines as they don't pull the proxy config.

![image](https://user-images.githubusercontent.com/1717238/49174175-3db10000-f30b-11e8-8d12-367c7c5efd31.png)

I'm unable to test this locally as I can't quite figure out how to get it to test off of my own install script (appears to be pulling from elsewhere?) but it should be fixable by introducing an env of the configured proxy (`http_proxy=<proxy>`) or by possibly even prefacing the lines with `sudo -E`.

https://github.com/GNS3/gns3-vm/blob/36fd90f0156f7833b6d8d73536da54aef1789050/config/install.sh#L46

**Comment by grossmj** [comment]
I couldn't test since I don't have a proxy. Please comment if this still does not work.

**Comment by RyanBreaker** [comment]
Sorry for the late response, I'm still getting the same error.

**Comment by RyanBreaker** [comment]
I'm doing some of my own testing, where is the welcome.py for the GUI ran from? I make edits locally to point to my own fork but it keeps being overwritten, and the only one I can find is in /tmp/{gns3dir}/scripts/welcome.py, which keeps being overwritten by the GNS3 tar and not my own.
