### ISSUE TITLE
Move Docker data to /opt

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-vm#114]
Currently docker stores all it's data (images/container) in /var/lib/docker. That means it resides in the root filesystem. I suggest to store these data in the /opt filesystem, for example into /opt/docker.

In the current stable gns3-vm you have to change DOCKER_OPTS in /etc/default/docker to `DOCKER_OPTS="-g /opt/docker"`, I don't know how that can be achieved in the bionic branch.

**BUT** changing the directory results in the loss of all previously downloaded docker images. So I won't change any existing VM. But maybe it can be introduced in the bionic branch.

**Comment by ehlers** [comment]
Changing docker options in systemd systems, it should apply also to bionic:
- The old /etc/default/docker still exists, but using it for configuring your Docker daemon is discouraged.
- The recommended way is using /etc/docker/daemon.json. It's main drawback is, that you can't change options, that are set on the command line. Currently the only option set in /lib/systemd/system/docker.service is `-H` (hosts), so all other options can be set in daemon.json.
  For details, see <https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file>. To set the docker data dir, use this configuration:
  ```
  {
      "data-root": "/opt/docker"
  }
  ```
  Afterwards restart docker with `sudo systemctl restart docker.service`.
- Systemd configuration file
  Create a file in /etc/systemd/system/docker.service.d, for example gns3-docker.conf
  ```
  [Service]
  ExecStart=
  ExecStart=/usr/sbin/dockerd -g /opt/docker -H fd://
  ```
  Then reload the systemctl configuration with `sudo systemctl daemon-reload`, afterwards restart Docker with `sudo systemctl restart docker.service`.

**Comment by grossmj** [comment]
Implemented. Thanks :+1:
