### ISSUE TITLE
Issue: pip incorrectly getting empty proxy variable passed

### ISSUE THREAD

**Issue by Sloanstar** [GNS3/gns3-vm#120]
https://github.com/GNS3/gns3-vm/commit/913bf545b2d6e9860e12cfb92f57babdccf500e6

Commit to enhance proxy support for pip in update script has a logic error - incorrectly negating the -z test. (My fault)

Corrected affected update scripts.
Pull request created.
https://github.com/GNS3/gns3-vm/pull/119

**Comment by grossmj** [comment]
No worries. Thanks for the fix.
