### ISSUE TITLE
Fix high I/O polling rate for some appliances

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-vm#128]
See https://gns3.com/community/discussion/cpu-usage-2

This can be fixed by configuring a KVM parameter as described in https://codingpackets.com/blog/kvm-host-high-cpu-fix/ which we could do permanently in the GNS3 VM.

I don't know if Qemu 3.1.0 has the same problem.

**Comment by grossmj** [comment]
@b-ehlers just wondering if have you faced this issue with Qemu 3.1.0?

**Comment by b-ehlers** [comment]
I haven't noticed this issue, but I'm not using Cisco CRS1000v and Juniper vMX. So perhaps I'm just lucky using the more lighter VMs.

If I understand correctly, the halt_poll_ns parameter tells the KVM module to poll for some wakeup condition for a certain time before it halts a vCPU. So I expect that this is independent of the qemu version, it's a function of KVM.

I just changed the halt_poll_ns parameter in my system. But as I haven't noticed this issue, I don't expect any change. For me It's more a safety guard, so I wouldn't run into that in the future.

**Comment by grossmj** [comment]
Fixed in version 2.2

**Comment by andrej-korshikov** [comment]
I can confirm that `# echo 0 > /sys/module/kvm/parameters/halt_poll_ns` is definitely the thing. Without this setting just one Juniper vMX 18.2R1.9 VFP (linecard) constantly consume 100% CPU. And with `halt_poll_ns = 0` my CPU utilization is about 30%, so I can easily start three routers (each with one RE and one PFE) even on my weak dual-core laptop.
