### ISSUE TITLE
Dependency Problems Upgrading 2.2.0b1 to 2.2.0b3

### ISSUE THREAD

**Issue by yuljk** [GNS3/gns3-vm#129]
Hi - When performing an upgrade from the console in the GNS3-VM running 2.2.0b1 to 2.2.0b3 I get the following dependency errors and the upgrade fails.

`Log started: 2019-06-24  15:23:52
Setting up libssl1.1:amd64 (1.1.1-1ubuntu2.1~18.04.3) ...
Checking for services that may need to be restarted...done.
Checking for services that may need to be restarted...done.
Checking init scripts...
dpkg: error processing package libssl1.1:amd64 (--configure):
 installed libssl1.1:amd64 package post-installation script subprocess returned error exit status 10
dpkg: dependency problems prevent configuration of libdns-export1100:
 libdns-export1100 depends on libssl1.1 (>= 1.1.0); however:
  Package libssl1.1:amd64 is not configured yet.

dpkg: error processing package libdns-export1100 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of openssl:
 openssl depends on libssl1.1 (>= 1.1.1); however:
  Package libssl1.1:amd64 is not configured yet.

dpkg: error processing package openssl (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libdns1100:amd64:
 libdns1100:amd64 depends on libssl1.1 (>= 1.1.0); however:
  Package libssl1.1:amd64 is not configured yet.

dpkg: error processing package libdns1100:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bind9-host:
 bind9-host depends on libdns1100 (= 1:9.11.3+dfsg-1ubuntu1.8); however:
  Package libdns1100:amd64 is not configured yet.

dpkg: error processing package bind9-host (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libisc169:amd64:
 libisc169:amd64 depends on libssl1.1 (>= 1.1.0); however:
  Package libssl1.1:amd64 is not configured yet.

dpkg: error processing package libisc169:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libisccc160:amd64:
 libisccc160:amd64 depends on libisc169 (= 1:9.11.3+dfsg-1ubuntu1.8); however:
  Package libisc169:amd64 is not configured yet.

dpkg: error processing package libisccc160:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libisc-export169:amd64:
 libisc-export169:amd64 depends on libssl1.1 (>= 1.1.0); however:
  Package libssl1.1:amd64 is not configured yet.

dpkLog ended: 2019-06-24  15:23:53
`
Many thanks

**Comment by grossmj** [comment]
I got the same error but I thought it was only... I will upload a fix soon.

**Comment by yuljk** [comment]
Many thanks Jeremy.

**Comment by grossmj** [comment]
Looks like this is a problem on Ubuntu's side: https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1832919

This can be fixed by starting a shell in the GNS3 VM and executing the following commands:

```
sudo dpkg-reconfigure libc6
sudo dpkg --configure libssl1.1
```

**Comment by grossmj** [comment]
I included this fix in our upgrade script. Please try to upgrade the VM again.

**Comment by grossmj** [comment]
Only one issue left is that the non interactive upgrade is not recognized and a question is asked. Could be related to this Ubuntu issue: https://bugs.launchpad.net/ubuntu/+source/ansible/+bug/1833013

**Comment by grossmj** [comment]
Ok, now the upgrade can be done without needing to answer any question. Please let me know if you still get an issue with this.

**Comment by yuljk** [comment]
I can confirm the changes to the script now resolve the dependency issues.  Many thanks Jeremy!
