### ISSUE TITLE
The 0.4 VM is too big

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-vm#13]
If you build the 0.4 tag you will get a big big VM:
![capture d ecran 2015-06-16 a 15 50 40](https://cloud.githubusercontent.com/assets/345437/8184587/7c39e71e-143f-11e5-806e-4d40a554a6c5.png)

**Comment by noplay** [comment]
vmware-vdiskmanager -k for shrink the vmdk change nothing

**Comment by noplay** [comment]
vmware-vdiskmanager -d for degragment change nothing

**Comment by noplay** [comment]
If confirm I just rebuild the 0.3 tag and the VM is 312 MB

**Comment by noplay** [comment]
The fun begin now. Git bisect on building the VM!

![MRW my girlfriend says our waitress is skanky because her thong is showing](http://i.imgur.com/1pLucmx.gif)

**Comment by noplay** [comment]
The issue is present in 1d29820

**Comment by noplay** [comment]
The issue is present in 030123b

**Comment by noplay** [comment]
The issue is not present in: cd94979f4942d4c265b1609caf369ac884aaf974

**Comment by noplay** [comment]
The issue is not present in: a1d4d09 OVF tools added just 20MB

**Comment by noplay** [comment]
The issue is not present in 2c4298488fbeaa239e2943cf55977b754a231acb

**Comment by noplay** [comment]
The regression is in 030123b but it's impossible :(

**Comment by noplay** [comment]
OH MY GOD

**Comment by noplay** [comment]
The commit has changed the order of the options in the menu. We need to press down one more time in order to access to the shell and type commands.

**Comment by noplay** [comment]
Also the change of order to the network interfaces froze the build because during the build the first should be a natted interface for the SSH of packer.

**Comment by grossmj** [comment]
> Also the change of order to the network interfaces froze the build because during the build the first should be a natted interface for the SSH of packer.

Weird because it worked here. By default the first interface is always NAT and I changed this only after the build is over (vmx_data_post). Anyway, this isn't a problem.

**Comment by noplay** [comment]
It seem packer 0.7.5 has issue with vmware fusion.
