### ISSUE TITLE
[GNS3 VM 2.2.0b3] QEMU 3.1.0 crashing on AMD Ryzen 5 CPU

### ISSUE THREAD

**Issue by SairusCZ** [GNS3/gns3-vm#130]
**Description**
When trying to start a QEMU in GNS3 VM 2.2.0b3 on host with AMD processor, QEMU crashes with the bellow error:

GNS3 Execution log:
> qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
> qemu-system-x86_64: error: failed to set MSR 0x10a to 0x0
> qemu-system-x86_64: /build/qemu-uCKref/qemu-3.1+dfsg/target/i386/kvm.c:2207: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.`
> 

GNS3 VM console:
> `gns3@gns3vm:~$ qemu-system-x86_64 -enable-kvm
> qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
> qemu-system-x86_64: error: failed to set MSR 0x10a to 0x0
> qemu-system-x86_64: /build/qemu-uCKref/qemu-3.1+dfsg/target/i386/kvm.c:2207: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.
> Aborted
> 
> gns3@gns3vm:~$ qemu-system-x86_64 -enable-kvm -cpu host
> qemu-system-x86_64: error: failed to set MSR 0x10a to 0x8
> qemu-system-x86_64: /build/qemu-uCKref/qemu-3.1+dfsg/target/i386/kvm.c:2207: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.
> Aborted
> gns3@gns3vm:~$ qemu-system-x86_64 -enable-kvm -cpu base
> qemu-system-x86_64: error: failed to set MSR 0x10a to 0x0
> qemu-system-x86_64: /build/qemu-uCKref/qemu-3.1+dfsg/target/i386/kvm.c:2207: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.
> Aborted

**System details**
 - CPU: AMD Ryzen 2600
 - Hypervisor: VMWare Workstation 12 & 15
 - Virtualization is enabled in the host BIOS 
- Virtualization is enabled on the GNS3 VM 
- Tested with virtualized CPU counters ON and OFF
- KVM appears enabled on the VM
![image](https://user-images.githubusercontent.com/24818591/60206983-32986100-9855-11e9-8194-2d779e44811a.png)

![image](https://user-images.githubusercontent.com/24818591/60205671-16df8b80-9852-11e9-8eac-6c380a5f7628.png)

**NOTES**
-I have no issues on GNS3 VM 2.1.15 with QEMU 2.5.0 on the same AMD system. 

-Based on QEMU documentation this issue (for different AMD CPU) should have been resolved in QEMU 3.1.0 RC3 : https://wiki.qemu.org/Planning/3.1 

**Question**
Before I open a bug with QEMU, could you please confirm if the bellow bug fix is present in the GNS3 VM 2.2.0b3? 

https://bugzilla.redhat.com/show_bug.cgi?id=1655826

> gns3@gns3vm:~$ kvm -version
> QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-2ubuntu3)

**Comment by sairuscz** [comment]
I've reproduced the same issue on Ubuntu with QEMU 4.0.0. I will try to report the issue to them. 
You can close this ticket.

**Comment by grossmj** [comment]
@sairuscz thanks, I hope they going to fix this.

**Comment by 1001QAdotNET** [comment]
Damn ...I just hit the same bug !  Does anybody know of a workaround ? I could not make much sense of the bugzilla comments.

**Comment by grossmj** [comment]
Try to login to the GNS3 VM and spawn a shell, then type the following to install Qemu 2.11

```
sudo apt-get update
sudo apt-get install qemu=1:2.11+dfsg-1ubuntu7.15
```

Let me know if this solves your issue.

**Comment by grossmj** [comment]
An alternative to the commands above (not tested):

```
sudo apt-get purge qemu
sudo add-apt-repository -y --remove ppa:gns3/qemu
sudo apt-get update
sudo apt-get install qemu
```

**Comment by 1001QAdotNET** [comment]
the add-apt command does not work in that VM
/etc/apt/sources.list or the .d version do not have gns3 ppa record
purge qemu does not remove v 3.1
I managed to install v2.11 but the client does not see it

here is what a grep to the list of packages show for qemu

qemu/bionic,now 1:2.11+dfsg-1ubuntu7 amd64 [installed,upgradable to: 1:3.1+dfsg-2ubuntu3]
qemu-block-extra/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed,automatic]
qemu-kvm/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed]
qemu-slof/bionic,bionic,now 20170724+dfsg-1ubuntu1 all [installed,automatic]
qemu-system/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed,automatic]
qemu-system-arm/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed,automatic]
qemu-system-common/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed,automatic]
qemu-system-data/bionic,bionic,now 1:3.1+dfsg-2ubuntu3 all [installed,automatic]
qemu-system-gui/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed,automatic]
qemu-system-mips/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed,automatic]
qemu-system-misc/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed,automatic]
qemu-system-ppc/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed,automatic]
qemu-system-s390x/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed,automatic]
qemu-system-sparc/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed,automatic]
qemu-system-x86/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed]
qemu-user/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed,automatic]
qemu-user-binfmt/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed,automatic]
qemu-utils/bionic,now 1:3.1+dfsg-2ubuntu3 amd64 [installed,automatic]

**Comment by sairuscz** [comment]
Seems like compatibility issue between the Linux kernel and Qemu 3.1+.
I based the assumption on: https://forum.proxmox.com/threads/kvm-error-failed-to-set-msr-0x10a-to-0x0.55627/ 
 
I then upgraded the GNS3 VM to kernel 5.3.0 RC1 and I no longer receive the error message. However, some VMs do not start properly (just black screen). Other VMs start without any issues. 

I have not done much more testing yet.

**Comment by sairuscz** [comment]
Good news at last! After several kernel panics or other issues, I made everything work after kernel upgrade to v5.2.2 .

All VMs are now running seemingly without any issues or performance penalties. 
I only noticed the bellow notification message on Fortigate VM during bootup, however based on my research it can be ignored. 

`[Firmware Bug]: the BIOS has corrupted hw-PMU resources (MSR c0010000 is 530076)`




Stock GNS3 VM 2.2.0b3:
------------------------------
```
gns3@gns3vm:~$ uname -a
Linux gns3vm 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
gns3@gns3vm:~$
gns3@gns3vm:~$ qemu-system-x86_64 -enable-kvm
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
qemu-system-x86_64: error: failed to set MSR 0x10a to 0x0
qemu-system-x86_64: /build/qemu-uCKref/qemu-3.1+dfsg/target/i386/kvm.c:2207: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.
Aborted
```



UPGRADE KERNEL PROCESS:
----------------------------
```
sudo apt-get update
sudo apt-get upgrade
###PROMPT: Configuring libssl1.1:amd64 >>>>> Restart services during package upgrades without asking?   >>> YES

cd /tmp/
wget -c https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.2.2/linux-headers-5.2.2-050202_5.2.2-050202.201907231250_all.deb
wget -c https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.2.2/linux-headers-5.2.2-050202-generic_5.2.2-050202.201907231250_amd64.deb
wget -c https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.2.2/linux-image-unsigned-5.2.2-050202-generic_5.2.2-050202.201907231250_amd64.deb
wget -c https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.2.2/linux-modules-5.2.2-050202-generic_5.2.2-050202.201907231250_amd64.deb
sudo dpkg -i *.deb

sudo reboot

```

After Upgrade GNS3 VM 2.2.0b3 to kernel 5.2.2-050202-generic:
------------------------------
```
gns3@gns3vm:~$ uname -r
5.2.2-050202-generic
gns3@gns3vm:~$ qemu-system-x86_64 -enable-kvm
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
VNC server running on ::1:5900

gns3@gns3vm:~$ qemu-system-x86_64 -name FortiGate6.2.0-1 -m 1024M -smp cpus=1 -enable-kvm -machine smm=off -boot order=c -drive file=/opt/gns3/projects/7e333392-1a44-4d6b-a07f-4c54e32dc55e/project-files/qemu/65a1e817-b435-4cf0-9f6b-a29f4859ea53/hda_disk.qcow2,if=virtio,index=0,media=disk -drive file=/opt/gns3/projects/7e333392-1a44-4d6b-a07f-4c54e32dc55e/project-files/qemu/65a1e817-b435-4cf0-9f6b-a29f4859ea53/hdb_disk.qcow2,if=virtio,index=1,media=disk -uuid 65a1e817-b435-4cf0-9f6b-a29f4859ea53 -serial telnet:127.0.0.1:5001,server,nowait
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
VNC server running on ::1:5900

```


No issues I can start and run all VMs now. Sweet :-)

**Comment by 1001QAdotNET** [comment]
I can confirm that the above worked, Good work! Thanks a lot you saved me a lot of time , really  grateful for this

**Comment by grossmj** [comment]
Great, thanks for this :)

**Comment by jvanderaa** [comment]
Thanks for this update! Very helpful on older as well 2.1.21

**Comment by dmfigol** [comment]
I have Ryzen 3000 and had the same problem. The above solution fixed it.
@grossmj, would it be possible to include the upgraded kernel in the GNS3 VM to mitigate this problem in the first place?

**Comment by jcoghill** [comment]
Huge help! Greatly appreciated for the help.

**Comment by grossmj** [comment]
I am going to consider including an upgraded kernel in the GNS3 VM

**Comment by jeremy-petrusma** [comment]
Fix worked for me too on Ryzen 2200G. Thanks a million!

**Comment by grossmj** [comment]
Would installing the HWE stack solve this problem? 

https://wiki.ubuntu.com/Kernel/LTSEnablementStack

All you have to do is type the following command: `sudo apt-get install --install-recommends linux-generic-hwe-18.04` and reboot.

However, I cannot test since I don't have an AMD Ryzen CPU. Please can someone test this?

Thanks.

**Comment by jeremy-petrusma** [comment]
Unfortunately installing HWE stack didn't resolve the issue. I started with a fresh GNS3 VM, needed to do  `sudo apt-get update` before `sudo apt-get install --install-recommends linux-generic-hwe-18.04`. Stack installs kernel version 5.0.0-31-generic.

```
gns3@gns3vm:~$ uname -r
5.0.0-31-generic
```
I still get this KVM acceleration error, I also tried disabling KVM in the config file but still just seems to throw the same error.

```
[Qemu]
enable_kvm = false
```

`KVM acceleration cannot be used (/dev/kvm doesn't exist). It is possible to turn off KVM support in the gns3_server.conf by adding enable_kvm = false to the [Qemu] section`.

**Comment by sairuscz** [comment]
I may have forgotten to mention, but I've tested more than 15 kernel versions before I found that 5.2.2 works. Clearly I did not test all existing builds but all previous versions either resulted in kernel panic or did not fix the MSR issue.

**Comment by sairuscz** [comment]
> Unfortunately installing HWE stack didn't resolve the issue for me on Ryzen 2200G. I started with a fresh GNS3 VM, needed to do `sudo apt-get update` before `sudo apt-get install --install-recommends linux-generic-hwe-18.04`. Stack installs kernel version 5.0.0-31-generic.
> 
> ```
> gns3@gns3vm:~$ uname -r
> 5.0.0-31-generic
> ```
> 
> I still get this KVM acceleration error, I also tried disabling KVM in the config file but still just seems to throw the same error.
> 
> ```
> [Qemu]
> enable_kvm = false
> ```
> 
> `KVM acceleration cannot be used (/dev/kvm doesn't exist). It is possible to turn off KVM support in the gns3_server.conf by adding enable_kvm = false to the [Qemu] section`.

Based on your output, I would guess that you forgot to enable AMD-V.

**Comment by grossmj** [comment]
Thanks for testing :+1: I will add the kernel v5.2.2 to the VM update script soon.

**Comment by jez81** [comment]
> Based on your output, I would guess that you forgot to enable AMD-V.

Thanks for the feedback, are you talking about the bios setting?. I didn't have to enable AMD-V with the 5.2.2 kernel fix.

**Comment by sairuscz** [comment]
@grossmj ,  I've now tested the kernel 5.0.0-31-generic which came with the HWE update and QEMU indeed works. You have some great intuition!

Steps I did:
1)Deploy new GNS3 VM 2.2.0 in VMWare Player
2)Enable AMD-V for the GNS3 VM (still not enabled by default)
3)Updated the VM with the bellow commands:
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install --install-recommends linux-generic-hwe-18.04
reboot
4)Test QEMU VMs and they started without any issues.

**Comment by sairuscz** [comment]
> > Based on your output, I would guess that you forgot to enable AMD-V.
> 
> Thanks for the feedback, are you talking about the bios setting?. Is is enabled in the bios, however I didn't have to enable AMD-V with the 5.2.2 kernel fix.

AMD-V must already be enabled in your BIOS, however, you will also need to enable it in the GNS3 VM properties.
![image](https://user-images.githubusercontent.com/24818591/66626967-6fb51300-ebfa-11e9-8766-f609d8b77da8.png)

**Comment by jez81** [comment]
Ahhh, thanks, that's what I'm missing , I will give that a go.

**Comment by jez81** [comment]
Thanks @SairusCZ , enabling AMD-V in the VM properties resolved the issue.

**Comment by grossmj** [comment]
I have added the 5.2.2 kernel fix to the GNS3 VM upgrade script. Just upgrade your GNS3 VM and everything should be good after. Next versions of the GNS3 VM will include the 5.2.2 kernel.

**Comment by grossmj** [comment]
The 5.2.2 kernel fix now prevents GNS3 VM to properly work on Hyper-V. GNS3 cannot see the IP address of the VM using LIS (Linux Integration Services, package installed: linux-virtual linux-cloud-tools-virtual and linux-tools-virtual).

All our problems come from backporting Qemu 3.1.0 into Ubuntu 18.04. The original idea is this version solves some issues like described in https://www.bernhard-ehlers.de/blog/2017/08/11/gns3-qemu-issues.html

I am considering reverting the default Qemu version 2.11.0 package. @b-ehlers do you have any input on this?

Finally, I just noticed that I overlooked that @SairusCZ said that the HWE update + Qemu 3.1.0 works, so I will use this instead of a forced upgrade to the v5.2.2 kernel (much cleaner too) if I can make the Linux Integration Services support work with the HWE kernel.

**Comment by grossmj** [comment]
> Finally, I just noticed that I overlooked that @SairusCZ said that the HWE update + Qemu 3.1.0 works, so I will use this instead of a forced upgrade to the v5.2.2 kernel (much cleaner too) if I can make the Linux Integration Services support work with the HWE kernel.

All I needed to do is install these packages:

`linux-virtual-hwe-18.04 linux-cloud-tools-virtual-hwe-18.04 linux-tools-virtual-hwe-18.04`

Now Hyper-V integration works with the HWE kernel.

**Comment by b-ehlers** [comment]
> I am considering reverting the default Qemu version 2.11.0 package. @b-ehlers do you have any input on this?
Not really. I don't have an AMD processor, don't use Hyper-V and I'm using Debian 10 (Buster) with it's kernel v4.19. In my environment QEMU 3.1 is working well. The issues I'm describing in my blog post were with QEMU v2.8 on Debian 9 (Stretch). So I have really no idea, how QEMU v2.11 is behaving in your environment.

**Comment by grossmj** [comment]
> Not really. I don't have an AMD processor, don't use Hyper-V and I'm using Debian 10 (Buster) with it's kernel v4.19. In my environment QEMU 3.1 is working well. The issues I'm describing in my blog post were with QEMU v2.8 on Debian 9 (Stretch). So I have really no idea, how QEMU v2.11 is behaving in your environment.

Ok, no worries. I think we will keep Qemu 3.1.0 by default and hopefully we won't hit more problems.

Thanks!
