### ISSUE TITLE
Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-vm#139]
Build the GNS3 VM based on Ubuntu 20.04 LTS, most likely starting with version 2.3 of GNS3

**Comment by dmfigol** [comment]
I even have a use-case which requires 20.04
Apparently latest IOL requires glibc 2.8+
```
./i86bi_linux_l2-adventerprisek9-ms-17.3-20201001 -e 4 -s 0 3
./i86bi_linux_l2-adventerprisek9-ms-17.3-20201001: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./i86bi_linux_l2-adventerprisek9-ms-17.3-20201001)
```
while 18.04 has 2.27. I looked through forums and it seems that general recommendation is not to upgrade glibc manually, since too many things depend on it

**Comment by grossmj** [comment]
Thanks for pointing that out. Next GNS3 release (v2.2.18) will have the GNS3 VM based on Ubuntu 20.04 LTS.

**Comment by grossmj** [comment]
The GNS3 VM since v2.2.18 uses Ubuntu 20.04 LTS
