### ISSUE TITLE
Projects and images not saved in /opt

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-vm#14]
A default server configuration should be created because currently projects and images are not saved in /opt.

**Comment by noplay** [comment]
It's a bug the config file is created but with the bad name
![capture d ecran 2015-06-18 a 12 34 28](https://cloud.githubusercontent.com/assets/345437/8229385/7ffb8470-15b6-11e5-973e-79644b106165.png)

**Comment by noplay** [comment]
Fixed
