### ISSUE TITLE
Version of the GNS3 VM for qemu

### ISSUE THREAD

**Issue by rcprior** [GNS3/gns3-vm#142]
Now that qemu for windows supports HAXM and WHPX, is there any chance a version of the GNS3 VM will be released for qemu? Since GNS3 already installs qemu, this would make it independent from externally installed hypervisors (VMWare or VirtualBox).

**Comment by grossmj** [comment]
We already distribute the GNS3 VM for Qemu/KVM, the latest version can be downloaded from https://github.com/GNS3/gns3-gui/releases/download/v2.2.5/GNS3.VM.KVM.2.2.5.zip

**Comment by rcprior** [comment]
Thanks! However, what would be the command line to run it? In linux we have virt-manager, but not in windows, and frequently you need a gazillion command line options to run a VM in qemu...
Ideally, the GNS3 itself would would start it with the appropriate options.
