### ISSUE TITLE
error during the upgrade!

### ISSUE THREAD

**Issue by lisi-if** [GNS3/gns3-vm#144]
`error: cannot update the ref 'refs/remotes/origin/2.2': unable to append to '.git/logs/refs/remotes/origin/2.2': Permission denied
From https://github.com/GNS3/gns3-server
 ! 60cc5c7b..4bed19f2  2.2        -> origin/2.2  (unable to update local ref)
error: cannot update the ref 'refs/remotes/origin/master': unable to append to '.git/logs/refs/remotes/origin/master': Permission denied
 ! 6d66e4d5..4bed19f2  master     -> origin/master  (unable to update local ref)
ERROR DURING THE UPGRADE PROCESS PLEASE, TAKE A SCREENSHOT IF YOU NEED SUPPORT`

**Comment by grossmj** [comment]
What was the issue?

**Comment by luismarichal** [comment]
Hello 

I have the same problem and cannot update from version 2.2.8 to 2.2.11.
Could you help me with how to resolve this issue?.

Thanks :)
-------
+ git reset --hard HEAD
HEAD is now at dadbacd8 Release v2.2.8
+ git fetch origin --tags
error: cannot update the ref 'refs/remotes/origin/2.2': unable to append to '.git/logs/refs/remotes/origin/2.2': Permission denied
From https://github.com/GNS3/gns3-server
 ! 54bab744..99128e77  2.2        -> origin/2.2  (unable to update local ref)
error: cannot update the ref 'refs/remotes/origin/master': unable to append to '.git/logs/refs/remotes/origin/master': Permission denied
 ! dadbacd8..c4d2422f  master     -> origin/master  (unable to update local ref)
ERROR DURING THE UPGRADE PROCESS PLEASE, TAKE A SCREENSHOT IF YOU NEED SUPPORT

**Comment by lisi-if** [comment]
Hey man what hypervisor are you using?




Kindly regards,


Elis







On Wed, Jul 15, 2020 at 8:52 PM +0200, "luismarichal" <notifications@github.com> wrote:















Hello


I have the same problem and cannot update from version 2.2.8 to 2.2.11.

Could you help me with how to resolve this issue?.
Thanks :)

git reset --hard HEAD

HEAD is now at dadbacd8 Release v2.2.8
git fetch origin --tags

error: cannot update the ref 'refs/remotes/origin/2.2': unable to append to '.git/logs/refs/remotes/origin/2.2': Permission denied

From https://github.com/GNS3/gns3-server

! 54bab744..99128e77  2.2        -> origin/2.2  (unable to update local ref)

error: cannot update the ref 'refs/remotes/origin/master': unable to append to '.git/logs/refs/remotes/origin/master': Permission denied

! dadbacd8..c4d2422f  master     -> origin/master  (unable to update local ref)

ERROR DURING THE UPGRADE PROCESS PLEASE, TAKE A SCREENSHOT IF YOU NEED SUPPORT

**Comment by luismarichal** [comment]
Hi,

Vmware ESXi
Version:6.5.0 Update 2 (Build 8294253)
