### ISSUE TITLE
GNS3 VM on xcp-ng

### ISSUE THREAD

**Issue by saviodsouza** [GNS3/gns3-vm#145]
Hi guys,

Is it possible to run gns3 vm in xcp-ng. https://xcp-ng.org/

its open source and can help to overcome the limitations of vmware esxi free version

what are your comments :)

https://gns3.com/community/discussion/xcp-ng-xen-server-not-possible

**Comment by grossmj** [comment]
I see xcp-ng is based on XenServer. So I think it is possible to run the GNS3 VM, for example by converting the GNS3 VM for VMware to XenServer: https://support.citrix.com/article/CTX116603

**Comment by saviodsouza** [comment]
Before conveting there has to be a cleanup and patch, i mean vmware guest has to be uninstalled and xen tools have to be installed.

can we have a xcp-ng vm in downloads sections like vmware and virtualbox

**Comment by grossmj** [comment]
I will look into that.

**Comment by saviodsouza** [comment]
I gave a try by importing gns3vm esxi to xcp-ng .
I could not uninstall the VMware tools as  vmware-uninstall-tools.pl did not run.
I installed xen-tools and rebooted.
Connected gns3-client to the vm and uploaded a vyos iso for testing.
Created a new project with a vyos node and nat
I enabled nested virtualization for the gns3vm
On start of the vyos node the vm  reboots and the client looses connection.

The Ubuntu guest Server runs smoothly it's only when I start the node it reboots.
I tried following the instructions of running gns3 remote server but it's for Ubuntu server 14.04

I even replaced trusty with bionic and it ran smoothly. But after importing the node in the project the symbols were missing.

Can you please give me guide lines how to install gns3server on a remote vm 18.04
