### ISSUE TITLE
I can't ping gateway from GNS3VM!

### ISSUE THREAD

**Issue by lisi-if** [GNS3/gns3-vm#147]
Hello, when i boot up gns3VM and GUI can't communicate with each other. But when i restart my laptop the problem resolved and i don't know why it is this issue? This is my configuration.
![Capture1](https://user-images.githubusercontent.com/62479542/80423151-c4db1c80-88df-11ea-8e4c-03a62b3fb96e.PNG)
![Capture2](https://user-images.githubusercontent.com/62479542/80423157-c60c4980-88df-11ea-9c8e-7e4b6e6d610a.PNG)

**Comment by grossmj** [comment]
Maybe your firewall is blocking the ping requests?

**Comment by lisi-if** [comment]
But why when i restart my laptop pinging works

**Comment by lisi-if** [comment]
i resolved, created new interface vmnet0(configured on gns3vm) and it works gns3VM can ping now his gateway.
