### ISSUE TITLE
[2.2.12] DUP packets when using Cloud node

### ISSUE THREAD

**Issue by jpobeda** [GNS3/gns3-vm#149]
Hi there,

I got 2.2.12 VM version running on ESXi (6.7) and when I make use of the Cloud object to connect lab to outside world I start seeing DUP packets.

I've googled a bit and there seemed to have happened before but fixed? Not sure what additional data would you guys need for this. Please advise.

**Comment by jpobeda** [comment]
@grossmj is this repo being actively looked at? Should I log this on gns3-server repo?

**Comment by grossmj** [comment]
Sorry, this repo wasn't actively monitored. Please open a new issue on gns3-server repo if you still experience DUP packets.
