### ISSUE TITLE
Windows appliance doesn't boot properly on 2.2.18

### ISSUE THREAD

**Issue by jerrylin1127** [GNS3/gns3-vm#151]
Hi folks,

I want to add Windows appliance (Windows 10 & Windows server 2012) on GNS3 2.2.18 with GNS3 VM (VMware Fiusion), but the console only repeat the status after "Booting from Hard Disk".

I also checked QEMU log and it displayed "qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]".

Linux based appliance is working ad well, and only Windows appliance have issue.

Does anyone faced this issue before?

gns3@gns3vm:/opt/gns3/projects/28e5bf2e-a86e-4323-af5a-714cc24b9efd/project-files/qemu/757d7905-45c2-4f82-9d06-f942a57d5e69$ cat qemu.log 

Start QEMU with /usr/bin/qemu-system-x86_64 -name TEST -m 1024M -smp cpus=1,sockets=1 -enable-kvm -machine smm=off -boot order=c -device ahci,id=ahci0 -drive file=/opt/gns3/projects/28e5bf2e-a86e-4323-af5a-714cc24b9efd/project-files/qemu/757d7905-45c2-4f82-9d06-f942a57d5e69/hda_disk.qcow2,if=none,id=drive0,index=0,media=disk -device ide-hd,drive=drive0,bus=ahci0.0,id=drive0 -uuid 757d7905-45c2-4f82-9d06-f942a57d5e69 -vnc 0.0.0.0:6 -monitor tcp:127.0.0.1:33559,server,nowait -net none -device e1000,mac=0c:9e:fd:5e:69:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:20089,localaddr=127.0.0.1:20088

Execution log:

qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]

**Comment by grossmj** [comment]
Do you have an AMD processor?

**Comment by jerrylin1127** [comment]
> Do you have an AMD processor?

No, I’m using MacBook Pro with Intel i9 9800H processor, and I also confirmed the VT-X has been enabled on GNS3 VM

**Comment by grossmj** [comment]
Do you confirm that the disk interface is set to "sata"?

**Comment by grossmj** [comment]
Could be worth to try to add one of the following "additional options" to see if this changes anything.

* `-cpu kvm64`
* `-cpu qemu64`
* `-cpu host`

**Comment by jerrylin1127** [comment]
> Could be worth to try to add one of the following "additional options" to see if this changes anything.
> 
> * `-cpu kvm64`
> * `-cpu qemu64`
> * `-cpu host`

I tried to change HDD interface with "sata", "ide" and "virtio" but still not worked.
For "-cpu kvm64" and "-cpu qemu64", it still stoked at "Booting from Hard Disk"
For "-cpu host", it displayed error message below, and it may cause by the bug with issue below.

https://github.com/GNS3/gns3-server/issues/1774

QEMU process has stopped, return code: -6
Start QEMU with /usr/bin/qemu-system-x86_64 -name NY-LAN-1 -m 2048M -smp cpus=2,sockets=1 -enable-kvm -machine smm=off -boot order=c -device ahci,id=ahci0 -drive file=/opt/gns3/projects/28e5bf2e-a86e-4323-af5a-714cc24b9efd/project-files/qemu/6dfd8d91-d00d-4236-a0ea-9d61ff36c762/hda_disk.qcow2,if=none,id=drive0,index=0,media=disk -device ide-hd,drive=drive0,bus=ahci0.0,id=drive0 -uuid 6dfd8d91-d00d-4236-a0ea-9d61ff36c762 -vnc 0.0.0.0:0 -monitor tcp:127.0.0.1:33687,server,nowait -net none -device e1000,mac=0c:9e:fd:c7:62:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:20023,localaddr=127.0.0.1:20022 -cpu host

Execution log:
qemu-system-x86_64: error: failed to set MSR 0x48d to 0x5600000016
qemu-system-x86_64: /build/qemu-Q4ciPO/qemu-4.2/target/i386/kvm.c:2691: kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.

**Comment by jerrylin1127** [comment]
I think it may relevant with platform and hypervisor.
Because it's working on Windows laptop with GNS3 2.2.18.

- Macbook Pro (i9 9880H) + VMWare Fusion 12.1.0 = Not working
- Windows laptop + VMWare Workstation Player 16 = Working

**Comment by grossmj** [comment]
@jerrylin1127 interesting, we have had some issues with AMD Ryzen CPUs in the past but your Macbook Pro has an Intel CPU. We definitely have to investigate this more...

You may want to try to enable "Virtualize CPU performance counters" but I doubt this is the problem.

![Screenshot from 2021-02-24 12-23-55](https://user-images.githubusercontent.com/4752614/108933520-33713e00-769b-11eb-98b9-04bf77035a5e.png)

Also, please try with the GNS3 VM 2.2.17 since the default Qemu version isn't the same.
