### ISSUE TITLE
Cannot exit logs in GNS3 VM 2.2.24

### ISSUE THREAD

**Issue by grimmer-std** [GNS3/gns3-vm#156]
Hi,
It looks like Ctrl+C (or suspend via Ctrl+Z) does nothing at the logs screen.
GNS3 VM version: 2.2.24
Virtualization software: VMware Workstation 16
Host OS: Windows 10 20H2

![image](https://user-images.githubusercontent.com/12690999/131504832-815f25f8-b99b-4bab-80aa-2307db17fcb4.png)

Stuff that might be helpful: I upgraded client and VM today, font in VM is different than the one that was default in version 2.2.23
I'm not sure if this issue was introduced in version 2.2.24 or if it was introduced in older version (I was never checking logs in versions prior to 2.2.24).

**Comment by grossmj** [comment]
Not sure what went wrong. I checked on v2.2.26 and could exit the logs.

**Comment by grimmer-std** [comment]
Well, I updated to v.2.2.27 and it is working as intended so all is good now 👍
