### ISSUE TITLE
gns3 vm 2.2.24 upgrade to 2.2.25 broken

### ISSUE THREAD

**Issue by jnatschev** [GNS3/gns3-vm#157]
hello.
i noticed an email message that 2.2.25 was released.
i started my gns3 vm 2.2.24 (i already had a snapshot)
at the information screen, i pressed enter
from the menu, i selected upgrade
i selected "Yes" from the next dialog
i hit enter on the already highlighted v2.2.25
the process went through the upgrade and the gns3 vm rebooted
after the boot up and return of the front menu, the version reported 2.2.17
i had installed gns3 gui 2.2.25 while the gns3 vm was upgrading and started gn3 gui and gns3 gui reported a version mismatch: gns3 gui 2.2.25, gns3 vm 2.2.17

**Comment by jnatschev** [comment]
did i jump the gun?

**Comment by grossmj** [comment]
I suspect an issue with setuptools that we have upgraded recently. I made a change to our upgrade scripts, please try if it fixes the issue on your side. You will have to restart the VM once and then start the upgrade.

**Comment by jnatschev** [comment]
just tried again. followed as close as possible the upgrade process. right at the very end the upgrade process said that the upgrade to 2.2.25 was done and wait 10 seconds. the vm rebooted and returned to the information screen with the gns3 server version at 2.2.17 again.

**Comment by jnatschev** [comment]
i just tried to upgrade to 2.2.24. the upgrade process succeeded. after the reboot, the gns3 server version was 2.2.17 again.

**Comment by jnatschev** [comment]
if there's something i can gather let me know how to gather it and i'll do it. i'm ok for now. i'm not going to use my snapshot. i can wait a bit before doing that.

**Comment by grossmj** [comment]
@jnatschev please can you try different upgrades, like going to 2.2.22 and then back to 2.2.25? Thanks 👍

**Comment by jnatschev** [comment]
going to 2.2.22 resulted in upgrade completed and upon reboot gns3 server version 2.2.17.
i still tried from here to upgrade to 2.2.25, same result, gns3 server version 2.2.17.

i just remembered something that may or may not be of value. when i performed a fresh installed the gns3 vm it was version 2.2.17.

**Comment by jnatschev** [comment]
potentially a file link issue. i did a bit of digging around and tried stuff manually.
gns3@gns3vm:~$ export PYTHONPATH="/usr/local/lib/python3.6/dist-packages/gns3_server-2.2.25-py3.6.egg"
gns3@gns3vm:~$ python3 -m gns3server --local
2021-09-15 01:15:02 INFO run.py:219 GNS3 server version 2.2.25
2021-09-15 01:15:02 INFO run.py:221 Copyright (c) 2007-2021 GNS3 Technologies Inc.
2021-09-15 01:15:02 INFO run.py:224 Config file /home/gns3/.config/GNS3/2.2/gns3_server.conf loaded
2021-09-15 01:15:02 WARNING run.py:230 Local mode is enabled. Beware, clients will have full control on your filesystem
2021-09-15 01:15:02 INFO run.py:244 Running with Python 3.6.9 and has PID 5216
2021-09-15 01:15:02 INFO run.py:79 Current locale is en_US.UTF-8
2021-09-15 01:15:02 INFO web_server.py:318 Starting server on 0.0.0.0:80
2021-09-15 01:15:02 INFO __init__.py:63 Load controller configuration file /home/gns3/.config/GNS3/2.2/gns3_controller.conf
2021-09-15 01:15:02 INFO __init__.py:67 Controller is starting
2021-09-15 01:15:03 INFO compute.py:64 Create compute local
2021-09-15 01:15:03 INFO compute.py:364 Connecting to compute 'local'
2021-09-15 01:15:03 CRITICAL web_server.py:88 Could not start the server: [Errno 13] error while attempting to bind on address ('0.0.0.0', 80): permission denied

the fact that it is permission denied doesn't bother me because the gns3 server is actually running. but part of the upgrade worked because 2.2.25 is there.

**Comment by jnatschev** [comment]
i tried again by restoring my pre upgrade snapshot (2.2.24). same result after the upgrade, gns3 server 2.2.17.

**Comment by grossmj** [comment]
There must be a problem with the GNS3 VM that came with v2.2.17 :thinking: I have downloaded the GNS3 VM for v2.2.24 and was able to switch between versions.

**Comment by jnatschev** [comment]
yeah. too right.
i reverted to my last known working gns3 vm, 2.2.24.
did a bit more digging around.
found that this directory "/usr/local/lib/python3.6/dist-packages" contained a directory named "gns3server".
i output the contents of the version.py file in this directory and it was, low and behold, 2.2.17.
i renamed this gns3server directory to gns3server.backup.
i ran the 2.2.25 upgrade process again.
hey presto! 2.2.25.
all is good with the world again. YAY!

out of curiosity, is there a procedure to migrate all relevant files of appliances and projects from one vm to another vm?
i tried searching for the answer and wasn't really able to find anything definitive; hence the question.

**Comment by warnesj** [comment]
Thanks @jnatschev!  Your workaround of renaming the /usr/local/lib/python3.6/dist-packages/gns3server directory and re-trying the update worked for me too.

**Comment by jnatschev** [comment]
Awesome.

Cheers,
John

**Comment by grossmj** [comment]
> out of curiosity, is there a procedure to migrate all relevant files of appliances and projects from one vm to another vm?
i tried searching for the answer and wasn't really able to find anything definitive; hence the question.

One way to do it is to use the "Migrate" option in the VM menu.

![Screenshot from 2021-09-17 17-14-19](https://user-images.githubusercontent.com/4752614/133744764-52be4d58-60c6-416e-88ab-73ae67bfc3ec.png)

**Comment by jnatschev** [comment]
cheers @grossmj. my apologies for even asking. i ought to have read the menu options before asking. i'm a dill.

**Comment by grossmj** [comment]
I changed the upgrade process to use PyPi instead of our GitHub repository: https://github.com/GNS3/gns3-vm/commit/08fd67d091e79a7944740cf73298914dce33ffd7

This should fix this issue and also allow for faster upgrades.

**Comment by jnatschev** [comment]
cool. thanks.
