### ISSUE TITLE
Change how the VM is restored (gns3restore)

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-vm#163]
> I usually run a production level GNS3 VM (1 or 2 releases back from the latest).  Then I run VMs for the two latest VMs.  I was using rsync to copy data from my production VM to my test VM for version 2.2.28 and after the rsync is setup you drop back to the cli with the message 'run sudo gns3restore if the menu didn't reappear'.  First, I've never fully understood why the menu doesn't restore (I've never seen it successfully restore once a CLI operation has taken place).  Second, when I did run the restore, it basically re-installs the entire VM and in that process it upgraded to the latest.  So my production build that was on a prior release got upgraded to the latest.  Is there a way we can prevent that by first detecting the version installed and then have the script only restore that version as opposed to upgrading?

**Comment by josephmhiggins** [comment]
..........have the gns3 user download the gns3 vm version that they were using....that's what I did when upgrading from 2.2.39 to 2.2.41. There are some bugs in the migration process somewhere and it took out gns3 2.2.39 information window. I read the code saw the incorrect script from 8 years ago:
https://raw.githubusercontent.com/GNS3/gns3-vm/master/scripts/update_2.1.sh

if [[ ! -d "gns3-server" ]]
there is no such directory.

I had to reinstall gns3 vm 2.2.39 so I could try to reproduce one of the bugs in the upgrade process.
