### ISSUE TITLE
GNS3 VM 2.2.35.1 vmx file corrupt | unable to import in VMware

### ISSUE THREAD

**Issue by mbardoscia** [GNS3/gns3-vm#168]
Hi, I'm trying to import vm into vmware but a vmx file corrupt message appear
![Schermata del 2022-12-18 20-24-37](https://user-images.githubusercontent.com/67555327/208315981-8689d5e7-db47-48ad-bab1-8fd868ad8a29.png)
OS fedora 36 kernel 6.0.12-200.fc36.x86_64
VMware Workstation 17 Pro

**Comment by grossmj** [comment]
Thanks for reporting. This could be something happening only in VMware Pro 17 since this version has recently been released.

I will try soon.

**Comment by mbardoscia** [comment]
I am still available to provide any logs if requested

**Comment by grossmj** [comment]
Do you still have the issue with v2.2.37?

**Comment by grossmj** [comment]
I have installed VMware Workstation 17 Pro on Ubuntu 22.04 LTS and got no issues importing the GNS3 VM ova v2.2.37
