### ISSUE TITLE
Multipath failures in the log

### ISSUE THREAD

**Issue by Kentzo** [GNS3/gns3-vm#173]
After downloading and importing the ova made for VMware with VMware Player you end up with a configuration that does not have "disk.enableUUID=TRUE". The net result is loads of annoying errors from the multipath service:

```
May 17 20:58:43 gns3vm multipathd[42561]: sdb: add missing path
May 17 20:58:43 gns3vm multipathd[42561]: sdb: failed to get udev uid: Invalid argument
May 17 20:58:43 gns3vm multipathd[42561]: sdb: failed to get sysfs uid: Invalid argument
May 17 20:58:43 gns3vm multipathd[42561]: sdb: failed to get sgio uid: No such file or directory
May 17 20:58:44 gns3vm multipathd[42561]: sda: add missing path
May 17 20:58:44 gns3vm multipathd[42561]: sda: failed to get udev uid: Invalid argument
May 17 20:58:44 gns3vm multipathd[42561]: sda: failed to get sysfs uid: Invalid argument
May 17 20:58:44 gns3vm multipathd[42561]: sda: failed to get sgio uid: No such file or directory
```

This is repeated every 5 seconds.

Please consider either modifying your distribution for VMware to have this setting or disable the multipath service in the VM.

**Comment by grossmj** [comment]
That should be fixed. Please let me know if you still have issues after the next release.
