### ISSUE TITLE
GNS3 VM arm64 issues with Docker containers

### ISSUE THREAD

**Issue by imyelmo** [GNS3/gns3-vm#179]
I have found  problems with Docker containers in gns3 2.2.45 (latest) and GNS3 VM arm64 2.2.45 (latest) from here: [https://github.com/GNS3/gns3-gui/releases/download/v2.2.45/GNS3.VM.ARM64.2.2.45.zip](https://github.com/GNS3/gns3-gui/releases/download/v2.2.45/GNS3.VM.ARM64.2.2.45.zip).

First, a problem related with the API version addressed here: [https://www.gns3.com/community/featured/docker-minimum-supported-api-version-error](https://www.gns3.com/community/featured/docker-minimum-supported-api-version-error). I solved it accordingly is stated in the link inside the VM.

Second, a problem related with busybox addressed here: [https://github.com/GNS3/gns3-server/issues/2069](https://github.com/GNS3/gns3-server/issues/2069). I solved it installing busybox-static package and copying the binary as it is suggested by the link inside the VM.

The changes mentioned above allow to run scenarios with Docker containers as expected. If you can address these issues and need a tester, let me know.

**Comment by grossmj** [comment]
> First, a problem related with the API version addressed here: https://www.gns3.com/community/featured/docker-minimum-supported-api-version-error. I solved it accordingly is stated in the link inside the VM.

Thanks I have fixed this in https://github.com/GNS3/gns3-server/commit/1f5085608ccc8a5494c1b6488f68652ba4f46d99

> Second, a problem related with busybox addressed here: https://github.com/GNS3/gns3-server/issues/2069. I solved it installing busybox-static package and copying the binary as it is suggested by the link inside the VM.

Fixed in https://github.com/GNS3/gns3-server/pull/2355

Next release should work a lot more smoothly, please don't hesitate to report if you find other issues in v2.2.46 (to be released soon). Thanks 👍

**Comment by imyelmo** [comment]
Thanks!
