### ISSUE TITLE
Hyper-v - GNS3-VM crashes every day

### ISSUE THREAD

**Issue by stijn-infini** [GNS3/gns3-vm#183]
Hello All,

I'm experiencing an issue with the GNS3 VM running on Hyper-V, where the VM crashes every day. I'm running version GNS3 version 2.2.47 and a windows server 2022 with Hyper-V. The crashes occur regardless of the network topology or load.

As a test, we set up a second GNS3 VM and have the same problems. Other VMs on the Hyper-V have no problems.
See below log capture on the Windows event viewer:

![GNS3 error](https://github.com/user-attachments/assets/4f058f51-5fd6-468a-9011-f7d2625cebd4)

Any guidance or solutions to resolve this problem would be greatly appreciated.

Thank you.
Stijn

**Comment by grossmj** [comment]
Unfortunately, the Hyper-V VM hasn't proven to be as stable as VMware or VirtualBox VMs: https://github.com/GNS3/gns3-server/issues/2371

I recommend switching to one of these hypervisors.

**Comment by stijn-infini** [comment]
Thanks for the info. We will consider to change.
