### ISSUE TITLE
GNS3VM v 2.2.48.1 for virtualbox doesn't start correctly

### ISSUE THREAD

**Issue by francesco-maria** [GNS3/gns3-vm#184]
The VM for virtualbox freshly downloaded, when imported on virtualbox 7.0.20 doesn't start correctly with error that you can see on the post below:

https://gns3.com/community/featured/gns3vm-for-virtualbox-2-2-48-1-doesnt-start-correctly
https://gns3.com/community/featured/gns3-vm-error-7

**Comment by grossmj** [comment]
That's strange, looks like the `cpu-checker` and `plymouth-themes` packages are missing.

**Comment by grossmj** [comment]
The current workaround is to issue the following commands in the VM:

```
sudo apt update
sudo apt install -y cpu-checker plymouth-themes
```

**Comment by grossmj** [comment]
I have added the missing packages for the next release. Hopefully, this will solve this issue.
