### ISSUE TITLE
Still issues upgrading: libvirt-daemon-system : Depends: polkitd (>= 121+compat0.1-2) but it is not installable

### ISSUE THREAD

**Issue by Eldiabolo21** [GNS3/gns3-vm#185]
Hi people, 

I'm trying update our gns3 VM from 2.2.43 to 2.2.48. 

However during install (and also when running `gns3restore`) I get 
```
[...]
+ apt-get install -y --allow-change-held-packages libvirt-daemon-system
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libvirt-daemon-system : Depends: polkitd (>= 121+compat0.1-2) but it is not installable
E: Unable to correct problems, you have held broken packages.
ERROR DURING THE UPGRADE PROCESS PLEASE, TAKE A SCREENSHOT IF YOU NEED SUPPORT
^CPlease run 'sudo gns3restore' in case the menu is no longer showing
```

This is related to https://github.com/GNS3/gns3-server/issues/2398 and [#2402](https://github.com/GNS3/gns3-server/issues/2402), how the solution doesnt work here. 
```
root@gns3vm:~# apt-mark showhold # Output is empty, so no held packages. 
root@gns3vm:~# apt-get install -y libvirt-daemon-system
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libvirt-daemon-system : Depends: polkitd (>= 121+compat0.1-2) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

According to this [issue on Launchpad](https://answers.launchpad.net/ubuntu/+source/libvirt/+question/709064) Its supposed to be a ubuntu repo problem? 

I'm not sure what to do. We didnt really change anything about the VM. 
Cheers and thanks

**Comment by grossmj** [comment]
> I'm trying update our gns3 VM from 2.2.43 to 2.2.48.

I have downloaded the GNS3 VM for v2.2.43 and upgraded to version 2.2.48. I didn't get any error.

Do you remember if the GNS3 VM you use had already been upgraded from an earlier version?

**Comment by grossmj** [comment]
Also, what is the output of the `sudo apt-cache policy libvirt-daemon-system` command? Thanks 👍

**Comment by Eldiabolo21** [comment]
Hey, thanks for your reply. 

The VM has definitely been update before at lest once if not twice. However, I'm not sure with which version we started with. 
Base-Image ist still ubuntu 20.04 if that relevant? 

```
root@gns3vm:~# sudo apt-cache policy libvirt-daemon-system
libvirt-daemon-system:
  Installed: 8.6.0-0ubuntu3.2~backport20.04.202305311233~ubuntu20.04.1
  Candidate: 10.0.0-2ubuntu8.2~backport20.04.202406082303~ubuntu20.04.1
  Version table:
     10.0.0-2ubuntu8.2~backport20.04.202406082303~ubuntu20.04.1 500
        500 http://ppa.launchpad.net/canonical-server/server-backports/ubuntu focal/main amd64 Packages
 *** 8.6.0-0ubuntu3.2~backport20.04.202305311233~ubuntu20.04.1 100
        100 /var/lib/dpkg/status
     6.0.0-0ubuntu8.20 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
     6.0.0-0ubuntu8.19 500
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     6.0.0-0ubuntu8 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages

**Comment by grossmj** [comment]
I think I understand what happened.

Looks like the Qemu version was upgraded (which is done by using the PPA ppa:canonical-server/server-backports repository). The same PPA is used when upgrading the libvirt-daemon-system package which result in the error you have seen.

Please can you try these commands:

```
sudo add-apt-repository -y --remove ppa:canonical-server/server-backports
sudo apt autoremove
sudo apt purge lvm2 
```

and then upgrade again.

**Comment by Eldiabolo21** [comment]
Thank you so much, that has done it!

**Comment by grossmj** [comment]
The libvirt package has been updated on the [Server Team Backports PPA ](https://launchpad.net/~canonical-server/+archive/ubuntu/server-backports/+packages?field.name_filter=&field.status_filter=published&field.series_filter=focal). This solves the issue without having to do the above workaround.

**Comment by jcalano** [comment]
disregard
