### ISSUE TITLE
 GNS3.VM.VMware.ESXI.3.0.0rc1 can not be imported on vSphere 7

### ISSUE THREAD

**Issue by Elfe** [GNS3/gns3-vm#187]
The GNS3.VM.VMware.ESXI.3.0.0rc1 template can not be imported into vSphere 7 as VMware seems to limit the video memory to 128000kb. The OVA want to assign 256MB video memory.

After untaring the ova and reducing the video memory in the template it was importing just fine.

I'm just wondering why the VM needs this much video memory?
Does it do anything else with it than displaying the text console? My GNS3 2.2 VM is working fine with 4MB of video memory.

**Comment by grossmj** [comment]
That must be some kind of default value.

So to understand, have you just edited the .ovf file to replace `<vmw:Config ovf:required="false" vmw:key="videoRamSizeInKB" vmw:value="262144"/>` to something like `<vmw:Config ovf:required="false" vmw:key="videoRamSizeInKB" vmw:value="4096"/>`?

**Comment by grossmj** [comment]
The next GNS3 VM for ESXi will have 4096 for 'videoRamSizeInKB'
