### ISSUE TITLE
sir, i use amd ryzen 9 8945H, iwanna asking to you ? why my GNS3 VM / KVM is not true , i had do it for make its TRUE  in all tutorial and forums, can you tell me why ?

### ISSUE THREAD

**Issue by fallss** [GNS3/gns3-vm#189]
![Screenshot 2024-09-24 215956](https://github.com/user-attachments/assets/5d8e1c7a-c671-4f4d-8d77-fc8f466cd5a5)

**Comment by fallss** [comment]
![image](https://github.com/user-attachments/assets/c59dc849-b5e5-477d-9cf9-cc703bc2fd26)
![image](https://github.com/user-attachments/assets/f15b428d-739d-4e5c-a395-71cc63d3e7e9)

**Comment by grossmj** [comment]
![Screenshot from 2024-10-23 11-27-22](https://github.com/user-attachments/assets/4605a15d-cef1-4675-9295-3884209ba19e)

Is nested VT-x/AMD-V enabled in the VirtualBox GNS3 VM settings?
