### ISSUE TITLE
Two small (potential) bugs

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-vm#2]
As I'm using linux, I don't need this GNS3 VM. But as I'm interesting how you make this VM I had a look at it. I think I found two small bugs in it:

http/preseed.cfg:
line 36: shouldn't it be fdisk /dev/sdb instead of /dev/sdb1 ?

scripts/provision.sh:
missing setcap for dynamips and iouyap

**Comment by noplay** [comment]
Thanks for preseed it's fixed.

What did you mean by setcap? Which command are you using?

**Comment by ehlers** [comment]
I mean setting the capabilities with the setcap command
I just see, that for iouyap, it's already done in "make install".

For dynamips, i'm not sure, but I think it's not in the Makefile, so you have to add something like:
setcap cap_net_raw,cap_net_admin+eip /usr/local/bin/dynamips

**Comment by ehlers** [comment]
I just had a look into the dynamips installation, I'm pretty sure it's not installed with elevated priorities (setcap cap_net_raw,cap_net_admin+eip /usr/local/bin/dynamips).

As GNS3 starts as user gns3, it won't be able to use the VM interfaces as cloud interfaces. But that may be intentional. It doesn't make too much sense, normally you would use the host interfaces for cloud.

**Comment by noplay** [comment]
I will take a look on that.

On Fri, May 1, 2015 at 11:28 AM, ehlers <notifications@github.com> wrote:

> I just had a look into the dynamips installation, I'm pretty sure it's not
> installed with elevated priorities (setcap cap_net_raw,cap_net_admin+eip
> /usr/local/bin/dynamips).
>
> As GNS3 starts as user gns3, it won't be able to use the VM interfaces as
> cloud interfaces. But that may be intentional. It doesn't make too much
> sense, normally you would use the host interfaces for cloud.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-packer/issues/2#issuecomment-98084958>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>
