### ISSUE TITLE
ovftool strips VT-x option

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-vm#20]
The virtualize VT-x option is not enabled when I import GNS3 VM.ova into VMware. It seems that ovftool strips the vhv.enable (VT-x virtualization) setting.

**Comment by noplay** [comment]
Mmmm I think we will replace the VMX from packer by our own it will be simpler than fighting with all tools

**Comment by noplay** [comment]
Oh I understand the issue. The ovftool convert a vmx to ovf file. We need to patch the OVF for adding the supported VT-x optons.
