### ISSUE TITLE
Problem when changing version to unstable

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-vm#23]
I couldn't change the GNS3 server to unstable in the VM. I had to use sudo to give me the right on the gns3_release file.

![upgrade_to_unstable](https://cloud.githubusercontent.com/assets/4752614/8505760/f875d69a-21ae-11e5-97eb-5c7d9b541575.png)

**Comment by grossmj** [comment]
Even after changing the file I noticed the VM was not upgraded to unstable:

![fail_to_upgrade_to_unstabe](https://cloud.githubusercontent.com/assets/4752614/8505840/a0dd3f1e-21b2-11e5-9037-72904806940e.png)

**Comment by noplay** [comment]
So the first error is fixed. 

I will try for the second. I'm worry that the data disk is not correctly mount at startup.
