### ISSUE TITLE
Splash screen should include "VM".

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-vm#37]
The splash screen should explicitly show this is the GNS3 VM. This is a bit of artwork ;)

**Comment by noplay** [comment]
We just need to change:
https://github.com/GNS3/gns3-vm/blob/master/plymouth/logo_wo_bar.png

**Comment by grossmj** [comment]
I think we can ask Steven and Ajay to work on this.

**Comment by grossmj** [comment]
and we should have a bug that the tongue can targets ;)

**Comment by noplay** [comment]
It's the last GNS3 VM issues!
