### ISSUE TITLE
Blocked upgrade

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-vm#38]
I got stuck there when trying to upgrade the VM. Impossible to answer or exit.

![blocked_upgrade](https://cloud.githubusercontent.com/assets/4752614/9073034/ff6a0d24-3abb-11e5-8603-823f9cbeac18.png)

**Comment by noplay** [comment]
You will need to run sudo dpkg-configure -a by hand  at next upgrade. But all the following will work
