### ISSUE TITLE
The VMware OVA is too big

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-vm#42]
Now it's 850mb...

**Comment by grossmj** [comment]
What changed?! :(

**Comment by noplay** [comment]
Don't know why perhaps related to the intyegration of the gns3 server and  it's only with vmware.

**Comment by noplay** [comment]
Finally I found the issue. Recent version of VMware embed the iso :P

**Comment by noplay** [comment]
But it's seem to be an old packer bug:
https://github.com/mitchellh/packer/issues/1083
