### ISSUE TITLE
why not use LVM to create volumes?

### ISSUE THREAD

**Issue by mrinaldhillon** [GNS3/gns3-vm#49]
Wouldn't it be nice If "opt" was installed using lvm as part of a volume group so that one could easily manage it i.e. modify size or attach another hdd? I had to use gparted on live cd to achieve the same on gns3 vm for opt and swap.

**Comment by grossmj** [comment]
:+1:

**Comment by grossmj** [comment]
Something like that should work (untested).

```
apt-get -y install lvm2

# Create the /opt disk
echo -e "o\nn\np\n1\n\n\nt\n8e\nw" | fdisk /dev/sdb

pvcreate /dev/sdb1
vgcreate vg1 /dev/sdb1
lvcreate -L 2G -n lvswap vg1
lvcreate -L 100%FREE -n lvdata vg1

mkswap -f /dev/mapper/vg1-lvswap
mkfs.ext4 /dev/mapper/vg1-lvdata

echo "/dev/mapper/vg1-lvdata  /opt  ext4  nodiratime  0  2" >> /etc/fstab
echo "/dev/mapper/vg1-lvswap  none  swap  sw  0  0" >> /etc/fstab
mount -a
```

**Comment by mrinaldhillon** [comment]
though swap should stay on /dev/sda along with root since HDD#2(/dev/sdb) for /opt should be independent so that we could move/copy it to another vm and used only for gns3 data.

**Comment by noplay** [comment]
If you unmount /opt you can resize it with resize2fs.

**Comment by noplay** [comment]
For me it's not require since we can already resize /opt.
