### ISSUE TITLE
Add a swap of 2GB

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-vm#50]

**Comment by noplay** [comment]
@jeremy I already have a swap of 2G. It seem to be the default behavior.

You can check if it's work for you by typing:
```
sudo swapon -s
``` 

It's /dev/sda5 for me.

**Comment by grossmj** [comment]
I confirm. My bad, mount doesn't show the swap ;)

**Comment by noplay** [comment]
I was thinking the same
