### ISSUE TITLE
Exception detected configuring IOS image

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-vm#54]
After uploading the IOS image, inside GNS3, Preferences > IOS > NEW > GNS3 VM >

The following error is given, and no image is listed. Fresh install, fresh config files, Win64 client, GNS3 VM.

****** Exception detected, traceback information saved in C:\Users\Ariel\AppData\Roaming\GNS3\exceptions.log ******

PLEASE REPORT ON https://community.gns3.com/community/software/bug

Traceback (most recent call last):
  File "./gns3-gui\gns3\http_client.py", line 718, in _processResponse
  File "./gns3-gui\gns3\dialogs\vm_with_images_wizard.py", line 166, in _getImagesFromServerCallback
KeyError: 'path'

**Comment by noplay** [comment]
You need to upgrade the VM. We have a bug if the version are not same in the GUI and in the VM.  In next beta we will show an error if you try to to use an old VM in a new GUI.

**Comment by codeassassin** [comment]
This is a screenshot showing the current build with error as described.

![image](https://cloud.githubusercontent.com/assets/6335629/10803900/03e4cea8-7d9b-11e5-9e58-4002bb4e2d72.png)
