### ISSUE TITLE
Cannot upgrade easily

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-vm#57]
With the latest GNS3 VM for version 1.4 beta 5.

When upgrading I came across this screen, impossible to select an option or even exit.

![upgrade_issue](https://cloud.githubusercontent.com/assets/4752614/11111109/8a4df078-88c2-11e5-8152-870e7784d051.png)

Must do an hard reset of the VM and try to upgrade again and manually enter this command to fix the upgrade.

![upgrade_failed](https://cloud.githubusercontent.com/assets/4752614/11111110/8be85b3a-88c2-11e5-89e7-a7eee3a4bd55.png)

Then I can finally select upgrade again in the menu to complete everything.

**Comment by noplay** [comment]
Strange we use:
```
sudo apt-get upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
```

**Comment by noplay** [comment]
The correct syntax seem to be:
```
sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade -y 
``` 

And I will add dpkg configure before all upgrade to avoid issues
