### ISSUE TITLE
Error in ReadMe

### ISSUE THREAD

**Issue by jprietove** [GNS3/gns3-vm#59]
Hello: trying to build a VirtualBox VM following the readme, I've found a (minor) error:

Instead of 
>./release_virtualbox.sh GNS3\ VM.ova 1.4.0

It should be

> ./release_virtualbox.sh 1.4.0 GNS3\ VM.ova

Maybe there is the same error in VMWare instructions

**Comment by noplay** [comment]
Thanks it's fixed
