### ISSUE TITLE
Install VMWare tools

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-vm#6]

**Comment by grossmj** [comment]
:+1:

**Comment by noplay** [comment]
https://www.packer.io/docs/builders/vmware-iso.html

**Comment by noplay** [comment]
Arg we have an issue:
``` 
tools_upload_flavor (string) - The flavor of the VMware Tools ISO to upload into the VM. Valid values are "darwin", "linux", and "windows". By default, this is empty, which means VMware tools won't be uploaded.
```

**Comment by grossmj** [comment]
What is it?

**Comment by ehlers** [comment]
Drawback of the VMware tools are, that you have to compile them from source (on linux).

An alternate solution is to ```apt-get install open-vm-tools-lts-trusty``` (in ubuntu 14.04).

Even VMware recommends open-vm-tools:
![vmware-live-cd-14](https://cloud.githubusercontent.com/assets/896406/8120338/58de2798-109e-11e5-9b72-e5cbbe0e1670.png)

**Comment by grossmj** [comment]
Excellent and a lot easier to install! Thanks :+1:
