### ISSUE TITLE
VirtualBox "message" GNS3-not-install

### ISSUE THREAD

**Issue by olegdunkan** [GNS3/gns3-vm#60]
I have GNS 1.3.13
First I have downloaded GNS3 VM 0.10.1.ova
Next I have imported it to VirtulaBox.
After starting VM I went to Log and saw:
start-stop-daemon: unable to stat ../gns3server (No such file or directory)
I have tried to connect http:/ip:8000/upload 
page not found 
It seems that gns3server is not in VM
I have tried to install it
via pip3 install gns3-server==1.3.13
Next see to Log and find out that some python module links aren't resolved, for example HttpConflict 
http:/ip:8000/upload doesn't uploaded to browser

How to properly install VM?

**Comment by noplay** [comment]
You have preinstalled VM here:
https://github.com/GNS3/gns3-gui/releases

Actually the GNS3 VM is only for the 1.4 release.

**Comment by olegdunkan** [comment]
Thank you!
