### ISSUE TITLE
Sometimes VMware invert adapters

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-vm#62]
Try to fix to the mac address

**Comment by grossmj** [comment]
Some input: https://communities.vmware.com/thread/454536?start=0&tstart=0

**Comment by noplay** [comment]
Hmm the mac address is correct. It's doesn't prevent the switching of the interface.

Example:
> eth0      Link encap:Ethernet  HWaddr 00:0c:29:85:51:40
>           inet addr:192.168.229.186  Bcast:192.168.229.255  Mask:255.255.255.0
>           inet6 addr: fe80::20c:29ff:fe85:5140/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:381 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:125 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000
>           RX bytes:55206 (55.2 KB)  TX bytes:25940 (25.9 KB)
>           Interrupt:19 Base address:0x2000
> 
> eth1      Link encap:Ethernet  HWaddr 00:0c:29:85:51:36
>           inet addr:172.16.16.150  Bcast:172.16.16.255  Mask:255.255.255.0
>           inet6 addr: fe80::20c:29ff:fe85:5136/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:255 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:26 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000
>           RX bytes:39538 (39.5 KB)  TX bytes:4046 (4.0 KB)

But discover the network adapter type is not the same:
```shell
gns3@gns3vm:~$ lspci -bv | grep -i ethernet -A1
02:00.0 Ethernet controller: Intel Corporation 82545EM Gigabit Ethernet Controller (Copper) (rev 01)
	Subsystem: VMware PRO/1000 MT Single Port Adapter
--
02:01.0 Ethernet controller: Advanced Micro Devices, Inc. [AMD] 79c970 [PCnet32 LANCE] (rev 10)
	Subsystem: Advanced Micro Devices, Inc. [AMD] PCnet - Fast 79C971
```

**Comment by noplay** [comment]
I confirm it seem the issue is due to the different type of network adapter.
