### ISSUE TITLE
Upgrade to 1.4.1 broken

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-vm#63]
Attempting to upgrade to 1.4.1, after selecting upgrade in the list, I ran into this.

![image](https://cloud.githubusercontent.com/assets/6335629/12796354/50258f58-ca8c-11e5-99f0-3100be544d5f.png)

**Comment by grossmj** [comment]
Thanks, in the meantime here is how to solve it: https://gns3.com/qa/upgrade-on-gns3-1-4-1-vm-vmware-

**Comment by codeassassin** [comment]
I ran: sudo pip3 install gns3-server==1.4.1

It seems to have worked. It gave me non-root errors unless I added sudo. Hopefully I haven't broken it doing it this way...

**Comment by noplay** [comment]
No problem. But apply the command and you will be able to make the next upgrade. I will make a fail safe command to fix the VM in case of another issue.
