### ISSUE TITLE
Do not erase user network interfaces after upgrade on ESXi

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-vm#65]

**Comment by noplay** [comment]
@grossmj  I suggest to drop the EXSi build with 1.5 and replace it by the remote install script (via a clean documentation).

Because the ESXi install should not be different of an install on any server provider.

**Comment by grossmj** [comment]
I would prefer to keep the ESXi VM to encourage users to use that. VIRL has a special image for ESXi too.

**Comment by noplay** [comment]
Fixed. We will need to think about pushing unstable to master in order to ship this to all users.
