### ISSUE TITLE
Latest release (0.10.4) VMware OVA Missing welcome.py

### ISSUE THREAD

**Issue by coxley** [GNS3/gns3-vm#66]
Latest release OVA for VMware is missing `/usr/local/bin/gns3-welcome.py` (that path may not be exact, from memory) so no menu at the start. `gns3recover` did its thing and rebooted to the same issue.

I had fetched the single file from `scripts/welcome.py` but many python3 libs were missing. 0.10.3 works fine though.

**Comment by noplay** [comment]
Thanks I will fix it

**Comment by noplay** [comment]
Fixed

Thanks for the report
