### ISSUE TITLE
VirtualBox VM network adapters order is wrong

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-vm#67]
I imported the latest GNS3 VM for version 1.4.3 in VirtualBox. First the default name was just vm (which I renamed to GNS3 VM) but more concerning, after some debugging I noticed that the adapters order is wrong, the host-only adapter is eth1 in Linux and the NAT adapter is eth0.

![gns3_vm_virtualbox_01](https://cloud.githubusercontent.com/assets/4752614/13195147/77df2422-d767-11e5-9b40-7990047c4ef2.png)

![gns3_vm_virtualbox_02](https://cloud.githubusercontent.com/assets/4752614/13195148/7c89b6cc-d767-11e5-95fe-edbd7c40b6f8.png)

That means GNS3 thinks that the NAT adapter IP address should be used to contact the GNS3 server running in the VM and the GUI will try to contact it for 120 seconds (progress dialog "Starting the GNS3 VM").

![gns3_vm_virtualbox_03](https://cloud.githubusercontent.com/assets/4752614/13195150/82815e90-d767-11e5-9d27-a897e5c49be1.png)

Apparently, the problem has appeared after version 1.4.1.

**Comment by grossmj** [comment]
Well... this is because I imported the OVA made for VMware... It was late ;)

**Comment by jtorri** [comment]
Actually, the changing order of nics in both Virtualbox VMs and VMWare VMs is something I have noticed for a while.  When GNS3 starts the VM the order of NICs (host only, NAT, bridged) is rarely consistent.  Occurs for me in GNS3 version 1.4.3 on Windows 8.1 but has been occurring for several previous releases.  I believe I commented on this earlier.  Thanks!

**Comment by noplay** [comment]
For VMware if you start with 1.4.0. You need to redownload the VM for 1.4.1 or in VMware settings be sure that the two adapaters have the same hardware type (e1000)
