### ISSUE TITLE
GNS3 version not updated after switching version

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-vm#73]
GNS3 version not updated on information screen after switching version (and auto reboot).

![gns3_vm_information_screen](https://cloud.githubusercontent.com/assets/4752614/15235544/9cdd0778-1879-11e6-94cf-ab5b8b9cb3b4.png)

Going to the menu and back doesn't help.

**Comment by grossmj** [comment]
Maybe a cache issue?

**Comment by noplay** [comment]
Hmm a mystery I was thinking it was due to unmerge branch. But I discover that the version is not updated when the update is run via VMware console, but work via SSH.

**Comment by noplay** [comment]
Fixed
