### ISSUE TITLE
Server still listen on port 8000 after switching to version 1.5

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-vm#74]
![gns3_vm_information_screen](https://cloud.githubusercontent.com/assets/4752614/15235544/9cdd0778-1879-11e6-94cf-ab5b8b9cb3b4.png)

![netstat_gns3_vm](https://cloud.githubusercontent.com/assets/4752614/15235611/21afb1f8-187a-11e6-88f6-29b09634afa8.png)

Additionally, the log entry in the menu doesn't work

**Comment by grossmj** [comment]
The log work after downloading the GNS3 VM for version 1.5.0 alpha 2, however the server still listens on port 8000 by default.

![gns3_vm_port](https://cloud.githubusercontent.com/assets/4752614/15235898/b79a40c8-187c-11e6-8c55-8508641424a5.png)

**Comment by noplay** [comment]
We forgot to merge the VM from unstable to master with the fixes related to port

**Comment by noplay** [comment]
Fixed
