### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-vm#75]
We need to allow configuration of the proxy for:

* [x] all our scripts (I think all of them use CURL but not sure)
* [x] apt-get
* [x] the docker daemon

https://gns3.com/qa/support-for-proxy-through-gns3-v

**Comment by noplay** [comment]
For docker:
https://crondev.com/running-docker-behind-proxy/

**Comment by ddompe** [comment]
From the UI standpoint, you need two entries to start with I think: http_proxy and https_proxy. Request the entries to specified as server and port.

* For all the scripts, you can enter the variables http_proxy and https_proxy on /etc/profile.d/proxy.conf. May require rebooting the VM to take effect if is already running. These variables requires to have the format 'http://<proxy>:<port>' (use http even for the https proxy)
* For apt-get, create an entry on /etc/apt/apt.conf.d/00proxy and add:
```
Acquire::http::Proxy "http://<proxy>:<port>";
```
* For docker the instructions that you found are right. It requires restarting docker daemon.

In general I would put some guideline on the UI saying that changing the proxy settings only takes effect after restarting the VM.

**Comment by noplay** [comment]
I think we will reboot the VM immediately like what we do for the upgrade

**Comment by noplay** [comment]
More details:
https://codepoets.co.uk/2014/debian-http_proxy-setting/

Why the hell their is not central file :(

**Comment by noplay** [comment]
It's more complicated the proxy could require a user and password

**Comment by ddompe** [comment]
ah, yes, user and password as well. but that just reduces to extra parameters in the syntax of the proxy definition when those are defined:

http://<user>:<password>@<proxy>:<port>

**Comment by noplay** [comment]
You can try by replacing /usr/local/bin/gns3welcome.py

By https://raw.githubusercontent.com/GNS3/gns3-vm/56137f64fe5a7cd868f119af5d850dfe44b7648d/scripts/welcome.py

**Comment by ddompe** [comment]
Thanks, I'm home today, but I will surely give it a try tomorrow when I'm back in the office

**Comment by ddompe** [comment]
Couple issues:

The file on /etc/profile.d/ has to end with a .sh extension, otherwise is not picked up. 
The apt.conf.d file is missing a ; at the end of the line.

**Comment by noplay** [comment]
Is it better with this version of the script?
https://raw.githubusercontent.com/GNS3/gns3-vm/161ae893e425c7ac8308ba18a676d8de0ff0289d/scripts/welcome.py

Thanks a lot for your help

**Comment by ddompe** [comment]
Perfect! Ship it!

**Comment by ddompe** [comment]
Mmmm, thinking twice about this, you should provide a way to define a no-proxy environment as well. For example I roam between the office and home, and I don't use a proxy at home. Maybe entering 'none' on the box, and as effect entering that entry commented out on the config files.

**Comment by noplay** [comment]
You can leave it blank

**Comment by noplay** [comment]
Shipping in progress :)

**Comment by ddompe** [comment]
Hi, I downloaded the latest VM for the 1.5 release in github, and didn't include this change...

**Comment by ddompe** [comment]
Ok, I tested with latest image, and realize there is one remaining bug:

https://github.com/GNS3/gns3-vm/blob/master/scripts/welcome.py#L246

That line was leave with a .conf extension, therefore the mv command is failing and the profile and docker are not being properly configured....

**Comment by noplay** [comment]
It's fixed thanks!

**Comment by ddompe** [comment]
Hi,

I just downloaded the 1.5.1 VM and seems like the bug is still there...

**Comment by noplay** [comment]
You are right the VM has not been rebuild from scrach for this release. I
will prepare the base VM for the 1.5.2

**Comment by skousout** [comment]
Still the same problem in 2.0.3
Upgrade script fails on "add-apt-repository -y ppa:gns3/qemu"
