### ISSUE TITLE
The VM is slow to shutdown

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-vm#76]
It takes a long time to shutdown the VM.

**Comment by noplay** [comment]
17 seconds for me, not sure what ubuntu is doing during this time.

**Comment by noplay** [comment]
Strangely Bernhard Ehlers doesn't seem to have the issue:
https://github.com/GNS3/gns3-server/issues/656#issuecomment-244067874

**Comment by noplay** [comment]
I have no idea what is happening in the background. I guess stuff like docker take some times to stop.

**Comment by ehlers** [comment]
My GNS3-VM is based on debian (currently testing/stretch, previously jessie) and shutdown of a VM is/was always faster. My installation is nothing special, just like your GNS3VM without the fancy scripts. I haven't done anything to tune the shutdown. The main difference is, that you are using ubuntu 14.04, which is upstart based, while both jessie and stretch are using systemd. I'm also using debian on my laptop with a full GUI. This machine is also quick shutting down.

I have also installed docker, but I'm using the latest version 1.12.1 with storage-driver overlay2 (aufs is no longer supported with debian stretch).

**Comment by ehlers** [comment]
Is this issue still there? At least on my Mac with VMware Fusion v8.5.8 both GNS3 v2.0 and v2.1 are shutting down in 1-2 seconds.

**Comment by grossmj** [comment]
The latest GNS3 VM is still quite slow to shut down on my system. I hope the move Ubuntu 16.04 could solve that https://github.com/GNS3/gns3-vm/issues/93 or maybe should we consider Debian?

**Comment by ehlers** [comment]
As I said, in VMware Fusion it's fast, both the GNS3VM 2.0 and 2.1. Maybe an issue with the VMware tools?

**Comment by grossmj** [comment]
Well, tested on another system (Windows) and it was fast too. My conclusion: it is not an issue with the VM itself.
