### ISSUE TITLE
Display the VM type in the info screen

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-vm#77]
We have problem people using the Vbox VM in VMware but  we have no way to verify it.

**Comment by noplay** [comment]
No way to get it we didn't save the info during the build process

**Comment by ehlers** [comment]
Easy way to determine virtualization technology:
http://unix.stackexchange.com/questions/89714/easy-way-to-determine-virtualization-technology

Tested within a WMware Fusion VM:
```
root@gns3vm:/home/gns3# dmidecode -s system-product-name
VMware Virtual Platform
```

Seems to work.

**Comment by noplay** [comment]
The problem is to detect for which type of VM we have build the VM. For example people using the ESXi VM in fusion and complaints that it's incorrect. I think we could improve that by improving the website.
