### ISSUE TITLE
exit Logs in GNS3 VM

### ISSUE THREAD

**Issue by davejumbi** [GNS3/gns3-vm#87]
how does one exit the logs CLI to back to the main GNS3 main menu , I'm stuck at the logs CLI, any help will be appreciated thanks

**Comment by noplay** [comment]
Ctrl + C should work

**Comment by davejumbi** [comment]
Hi noplay unfortunately its not working I'm just getting ^c if I type Ctrl+c

**Comment by noplay** [comment]
If you hit twice Ctrl + C ?

**Comment by noplay** [comment]
Work for me let me know if you have still the issue

**Comment by davejumbi** [comment]
still doesnt work , I gave up on it , whenever I check the logs I have to
shutdown

**Comment by noplay** [comment]
You are under vmware or VirtualBox? What is your host keyboard layout?

**Comment by davejumbi** [comment]
vmware workstation , I'm using an american keyboard layout

**Comment by noplay** [comment]
Hi,

I change the way we display logs. If you upgrade the VM via the menu Ctrl + C should work better now.

Thanks for the report

**Comment by a-wip0** [comment]
Doesn't work in vmware workstation 15. 
![Screenshot (47)](https://user-images.githubusercontent.com/33978908/60392279-b8542f00-9b29-11e9-9089-af20c0ebdf1a.png)

**Comment by grossmj** [comment]
I tested and it works on my VMware Workstaion 15.1 Pro.

**Comment by a-wip0** [comment]
yeah now its working for some reason.

**Comment by grossmj** [comment]
Okay, thanks for confirming this.

**Comment by choclambula** [comment]
still having the same problem in vmware 16.1

**Comment by s-celles** [comment]
I'm also facing a similar problem (with Proxmox 8.24)

CTRL + C displays ^C

need to type `exit` twice to go back to menu

```
gns3@gns3vm:~$ ^C
gns3@gns3vm:~$ exit
exit
Please run 'sudo gns3restore' in case the menu is no longer showing
gns3@gns3vm:~$ exit
```
