### ISSUE TITLE
UEFI boot?

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-vm#88]
NX-OSv 9000 requires UEFI for booting. I could get it running on my local Linux box with OVMF (following [this guide](https://github.com/tianocore/tianocore.github.io/wiki/How-to-run-OVMF)) by starting the VM with this command (device section omitted):

`/usr/bin/qemu-system-x86_64 -bios bios.bin -m 8096M -smp cpus=2 -enable-kvm -boot order=c -drive file=nxosv-final.7.0.3.I5.1.qcow2,if=ide,index=0,media=disk -serial telnet:0.0.0.0:5000,server,nowait -monitor tcp:127.0.0.1:38158,server,nowait -net none`

Does the GNS3 VM have this [BIOS file](https://sourceforge.net/projects/edk2/files/OVMF/OVMF-X64-r15214.zip/download)? If not, is it possible to add it in 1.5.3 / 2.0?

**Comment by adosztal** [comment]
Update: I copied the bios.bin to the GNS3 VM, now I can boot within that too with these settings:
![gns3_vm-uefi](https://cloud.githubusercontent.com/assets/16632791/20836340/2f0958e8-b89f-11e6-864d-aa16d7f44db1.png)

**Comment by noplay** [comment]
We have the seabios files:
![screen shot 2016-12-02 at 20 34 51](https://cloud.githubusercontent.com/assets/345437/20847546/ed2995e8-b8ce-11e6-817e-312863d6c698.png)

Do you think it could be one of them?

**Comment by adosztal** [comment]
Thanks, I'll check them.

**Comment by noplay** [comment]
Or perhaps we need this packages: https://launchpad.net/ubuntu/+source/edk2

**Comment by adosztal** [comment]
This is not available in the default repo but ovmf is. I'll start with SeaBIOS; if that doesn't work, I'll move to ovmf.

**Comment by adosztal** [comment]
SeaBIOS didn't help. I tried **bios.bin** as well as **bios-256k.bin** with no success.

I forgot that my box has newer Ubuntu; the Trusty repos contain neither edk2 nor ovmf. I could only install ovmf by downloading the [package](https://launchpad.net/ubuntu/utopic/amd64/ovmf/0~20131112.2590861a-2) and using dpkg:

```
wget https://launchpad.net/ubuntu/+source/edk2/0~20131112.2590861a-2/+build/5654556/+files/ovmf_0~20131112.2590861a-2_all.deb

gns3@gns3vm:~$ sudo dpkg -i ovmf_0~20131112.2590861a-2_all.deb 
Selecting previously unselected package ovmf.
(Reading database ... 27778 files and directories currently installed.)
Preparing to unpack ovmf_0~20131112.2590861a-2_all.deb ...
Unpacking ovmf (0~20131112.2590861a-2) ...
Setting up ovmf (0~20131112.2590861a-2) ...
```

Then I changed the bios file's path in the VM's advenced settings to **/usr/share/ovmf/OVMF.fd**; it boots.
Is this an acceptable way?

**Comment by noplay** [comment]
The GNS3 VM is build on a trusty. I think we could backport the package to trusty ppa.

But I don't know if the bios should not be a dependency file like an hda. It could be more flexible and futur proof.

**Comment by noplay** [comment]
What do you think about the idea of making the bios like a standard image? And we put a link to somewhere where you can download the bios.

**Comment by adosztal** [comment]
Backporting is easy because the package has no dependencies and doesn't require any compilation. If the package is installed from ppa, the path can be set as a qemu option in the template.

Making the bios as a standard image is indeed more future proof and, with the registry_version, we can make sure the template with the bios image can only be imported into the correct GNS3 version. The only drawback is that it requires more coding.

My suggestion is to go with the 2nd option. Can you include it in 2.0 or it will be pushed back to 2.1? Meanwhile I'll write a blog post with the workaround above, so people can start using N9kv until we have the final solution.

**Comment by noplay** [comment]
Support added but not tested in 2.0
