### ISSUE TITLE
Can't import the OVA on ESXi 6.5

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-vm#89]
The XML made for the OVF is not supported by the new ESXi web interface.

**Comment by noplay** [comment]
https://labs.vmware.com/flings/esxi-embedded-host-client/bugs/307#bug_comment_723

**Comment by noplay** [comment]
I fixed some issue but I'm blocked by this bug:
https://labs.vmware.com/flings/esxi-embedded-host-client/bugs/300

**Comment by noplay** [comment]
No new version from VMware we need to wait

**Comment by noplay** [comment]
VMware made an update but it's crash at the end of import

**Comment by noplay** [comment]
Fixed and documented

**Comment by elico** [comment]
@noplay Can you point me to the fix?

**Comment by noplay** [comment]
The documentation is here:
https://docs.gns3.com/1hEoK0rmtdBRnMaUaVoMHUbYwtDAltXYShiMJUp1GMxk/index.html#h.vxyo1vmd358z

> WARNING
VMware fixed the bug related to GNS3 after the official release of 6.5 so make sure to apply all updates. Especially you need to have the last web interface installed: https://labs.vmware.com/flings/esxi-embedded-host-client/
