### ISSUE TITLE
Hyper-V VM

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-vm#90]
No plan for a release but the status:
* 2.0 ship a new architecture for integrate new VM technology: (see: https://github.com/GNS3/gns3-server/tree/2.0/gns3server/controller/gns3vm)
* packer now support Hyper-V it should be possible to use it for building a VM

Issues:
* We don't have access to a development machine where Hyper-V is available
* We don't have access to a build machine where Hyper-V is available

**Comment by grossmj** [comment]
Maybe a solution: http://www.hurryupandwait.io/blog/creating-a-hyper-v-vagrant-box-from-a-virtualbox-vmdk-or-vdi-image

**Comment by grossmj** [comment]
I think the most straightforward way is to build for VirtualBox/VMware and then convert to Hyper-V.

**Comment by ziajka** [comment]
Makes sense to me.

**Comment by grossmj** [comment]
Implemented by https://github.com/GNS3/gns3-vm/commit/e394b2a7479e8b9cb0a50f9914d809d40b71c1a6 and https://github.com/GNS3/gns3-vm/commit/49262eb8b69636df145116ba374d7b07f3911730
