### ISSUE TITLE
Move to ubuntu 18.04

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-vm#93]
Current version is build on top of ubuntu 14.04. But a new LTS is available and seem stable now.

Advantages:
* Official qemu 2.5 instead of our backported version
* More recent KVM 
* Python 3.5 instead of 3.4
* SystemD instead of upstart (one day we will need to the switch)
* Python3 is the default python version no need for Python 2 :)
* We could stop releasing packages for trusty (not now, but it's allow us to stop if we need)

I see only one disadvantage:
* Require some work for the migration

**Comment by grossmj** [comment]
I am for moving to 16.04

**Comment by noplay** [comment]
Ok now the install work but:
* GNS3 don't start (normal we need to switch to systemd)
* The splashscreen is missing
* The autologin is broken

**Comment by noplay** [comment]
* Splashscreen is half working (the background image disapear ...)
* Autologin is OK
* The size of the VM is 1.5GB the free disk process no longer seem to work

**Comment by noplay** [comment]
* Splashscreen is half working (the background image disapear ...)
* size of the VM is ok
* detection of the GNS3 VM is broken

**Comment by noplay** [comment]
The move to systemd is really painfull. At least the good news is the next move to another LTS will probably be less problematic

**Comment by noplay** [comment]
Current issue is when the eth0 got an ip the network freeze due to a conflict between vmtools and finishing the network configuration...

**Comment by noplay** [comment]
The IP is ok now

**Comment by noplay** [comment]
And plymouth also. Now rebuilding a clean VM to allow some users to test. 

The upgrade process from 14.04 will be missing.

**Comment by noplay** [comment]
Andrew has tested:
* Sometimes the VM boot and eth0 is not detected on the first VM screen
*  His GNS3 never detected the ip of the VM

**Comment by noplay** [comment]
Issues solved but I found a new.

The eth1 is not up by default

**Comment by grossmj** [comment]
@noplay was this completed?

**Comment by grossmj** [comment]
@noplay what is the state of this?

**Comment by grossmj** [comment]
We will upgrade to 18.04 instead.

https://gns3.com/qa/can-the-gns3-vm-be-upgraded-from

**Comment by ehlers** [comment]
Just a warning:

The package x11vnc has a serious bug since Debian 9 / Stretch https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=859213 and Ubuntu 17.04 / Zesty (including Ubuntu 18.04 / Bionic Beaver) https://bugs.launchpad.net/ubuntu/+source/x11vnc/+bug/168608). Even though the bug reports are older than a year and patches are available, this bug has not yet been resolved in Debian and Ubuntu. The good news is, that x11vnc got a new maintainer, so there is a chance that this finally gets some attention.

x11vnc is used only, when a docker container uses a GUI. Mainly during showing a popup x11vnc crashes. Then the user has to stop the docker container and start it again. As this happens quite often it's really annoying.

**Comment by grossmj** [comment]
The x11vnc package hasn't been updated so far. This would leave us 2 options: compile it or build a new deb package (which we would put on our PPA).

**Comment by ehlers** [comment]
A quick-and-dirty method would be to use x11vnc from cosmic, but that's not a stable solution. So maintaining an own x11vnc package seems to be the only immediate solution.

I'm really disappointed by the poor maintenance of x11vnc, so a longterm solution would be to look for an alternative. From what I have read it might be possible to replace x11vnc + xvfb by a vnc server, for example tightvncserver or tigervnc-standalone-server. But I haven't tested that (nor do I have any plans for that).

**Comment by ehlers** [comment]
Debian 9.6 (released 2018-11-10) updates x11vnc to v0.9.13-2+deb9u1, which solves the x11vnc bug. Ubuntu 18.04 not yet fixed.

**Comment by grossmj** [comment]
We have a new GNS3 VM based on Ubuntu 18.04 now, branches are bionic-stable and bionic-unstable. It seems to work well, there will likely be some adjustments to be made after we do more tests.
