### ISSUE TITLE
Use a swapfile instead of a swap partition?

### ISSUE THREAD

**Issue by ianc1215** [GNS3/gns3-vm#94]
Just a thought, recently Ubuntu moved to using a swapfile instead of a swap partition.

Could the same thing be done with the GNS3server VM?

Just seems like it would be easier to adjust the swap file when introducing more memory into the system. That way you don't have to break out the partition editor.

**Comment by noplay** [comment]
Hi,

We are using the default settings of ubuntu installer. When we will release a VM based on 16.04 we will use the default settings, this should allow swap files.
