### ISSUE TITLE
The provided manifest file is invalid: Invalid OVF manifest entry: .

### ISSUE THREAD

**Issue by vasya4k** [GNS3/gns3-vm#96]
When trying to import ESXI OVA file into vCentre I get his "The provided manifest file is invalid: Invalid OVF manifest entry: .". I have investigated this myself and think this is because of 

in ~/Downloads/ova λ ovftool GNS3_VM.ovf gns3.ova
Opening OVF source: GNS3_VM.ovf
The manifest validates
Opening OVA target: gns3.ova
Writing OVA package: gns3.ova
Transfer Completed                    
Warning:
 - No manifest entry found for: 'GNS3_VM.ovf'.
 - File is missing from the manifest: 'GNS3_VM.ovf'.
Completed successfully

if I run 
~/Downloads/ova λ cat *.mf
SHA1(GNS3_VM-disk1.vmdk)= 8146362fe42e972e531c0e21c0ddb22a68dccf72
SHA1(GNS3_VM-disk2.vmdk)= 0dd9f76496cbd2cc6e014d03b9944704ef68ddeb

There is no entry for GNS3_VM.ovf 

Can someone please have a look. This is for GNS3.VM.VMware.ESXI.2.0.3.zip

**Comment by noplay** [comment]
Hi,

It's an ESXi bugs, you need the last last web interface:
http://docs.gns3.com/1hEoK0rmtdBRnMaUaVoMHUbYwtDAltXYShiMJUp1GMxk/index.html#h.vxyo1vmd358z
