### ISSUE TITLE
Vmnet on Mac OS X

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-vm#97]
Run the GNS3 VM using the native vmnet hypervisor on Mac OS X (similar to what Docker does).

**Comment by ehlers** [comment]
As ar as I know docker is using xhyve https://github.com/mist64/xhyve, but xhyve doesn't support nested virtualization, see https://github.com/mist64/xhyve/issues/47.

**Comment by grossmj** [comment]
Indeed, no nested virtualization is a big problem :(
