### ISSUE TITLE
Dev-Upgrade fails because of multidict

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-vm#98]
See https://www.gns3.com/qa/gns3-2-1-0dev5-to-2-1rc1-failed-

pip3 installation of multidict fails since it's upgrade to v3.2.0. That leads to a failure of the GNS3 VM upgrade of the dev channel (2.0dev or 2.1). Workaround is to stick with multidict==3.1.3.

**Comment by ehlers** [comment]
To correct this issue, choose one of these options:
* convince the devs of multidict to include multidict/_multidict.c in the tarball, see also issue https://github.com/aio-libs/multidict/issues/140.
* in requirements.txt restrict multidict to versions < 3.2.0.
* install cython from pypi (sudo pip3 install cython), the cython3 package from ubuntu 14.04 is too old to compile multidict.
* upgrade pip, newer versions will successfully install the wheel version from pypi. That's why only "old" linux versions, like ubuntu 14.04, have this issue.

**Comment by grossmj** [comment]
Thanks for tracking this down! :+1: 

I've restricted multidict to versions < 3.2.0 https://github.com/GNS3/gns3-server/commit/2a4ed9ba89c3d4364ecd4ccfb6e4a9719472c597

**Comment by ehlers** [comment]
Just tested the upgrade of the GNS3VM from 2.0.3 to 2.1, works fine.
