### ISSUE TITLE
Connection to GNS3 VM sometimes cannot be established

### ISSUE THREAD

**Issue by ugultopu** [GNS3/gns3-vm#99]
Version information
--------------------
1. macOS Sierra
2. GNS3 2.0.3
3. VirtualBox 5.1.28
4. GNS3.VM.VirtualBox.2.0.3

Steps to reproduce
-------------------
1. Start the GNS3 VM from VirtualBox or by starting GNS3 GUI.
2. Try to ping the IP address of the GNS3 VM from Terminal.app on macOS.

Expected results
----------------
1. Receiving response to ICMP request from the GNS3 VM.

Actual results
--------------
1. Sometimes, GNS3 VM does not respond to ICMP requests. After restarting the GNS3 VM, the problem is gone.
2. Sometimes, it is worse and GNS3 VM should be removed from VirtualBox and need to be imported again.

**Comment by grossmj** [comment]
Seems nobody else complained about this issue.
